// 语言包配置
export const LANGUAGES = {
  zh: {
    name: '简体中文',
    code: 'zh'
  },
  en: {
    name: 'English',
    code: 'en'
  }
};

// 语言存储键名
export const LANG_STORAGE_KEY = 'app_language';
export const LANGUAGE_CHANGED_EVENT = 'app:language-changed';

// 获取当前语言（仅 zh / en；与语言包 translations 键一致）
export function getLanguage() {
  const raw = uni.getStorageSync(LANG_STORAGE_KEY);
  return raw === 'en' ? 'en' : 'zh';
}

// 设置语言（写入 app_language，供全站 t() 使用）
export function setLanguage(lang) {
  const prev = getLanguage();
  const code = lang === 'en' ? 'en' : 'zh';
  if (prev === code) return false;
  uni.setStorageSync(LANG_STORAGE_KEY, code);
  if (typeof uni !== 'undefined' && typeof uni.$emit === 'function') {
    uni.$emit(LANGUAGE_CHANGED_EVENT, code);
  }
  return true;
}

// 语言翻译函数
export function t(key, lang = getLanguage(), params = {}) {
  const translations = {
    zh: {
      'home': '首页',
      'project': '项目',
      'add': '布置任务',
      'message': '消息',
      'profile': '我的',
      'login': '登录',
      'register': '注册',
      'settings': '设置',
      'language': '语言',
      'chinese': '简体中文',
      'english': '英文',
      'logout': '退出账号',
      'switch_account': '切换账号',
      'model_api': '员工与模型',
      'change_password': '修改密码',
      'workflow': '工作流',
      'profile_workflow_sub': '管理协作工作流流水线',
      'about': '关于',
      'version': 'v1.0',
      'collaboration_workbench': '协作工作台 · 竞赛项目',
      'interface_based_on_api': '界面以实际接口文档为准',
      'not_logged_in': '未登录',
      'click_to_login': '账号: 点击登录',
      'logged_in': '账号: 已登录',
      'phone': '手机号: ',
      'my_account': '我的账号',
      'hq_group': '全员群',
      'hq_subtitle': '共 {{ count }} 位数字员工 · 日报与总览发在本群',
      'loading': '加载中…',
      'send_message': '发送消息到全员群…',
      'send': '发送',
      'project_subtitle': '选择已有项目进入工作台，或新建一条协作流水线',
      'count_unit': '个',
      'no_workflow': '还没有工作流',
      'no_workflow_desc': '创建一个工作流后，可在「布置任务」里关联下发，或直接进入工作台查看任务与沟通。',
      'create_workflow': '创建工作流',
      'go_assign_task': '去布置任务',
      'name_required': '名称（必填）',
      'description_optional': '描述（可选）',
      'cancel': '取消',
      'create': '创建',
      'add_subtitle': '写清目标即可；默认从 <text class="em">产品部</text> 下发至 <text class="em">工程部</text>。',
      'select_workflow': '选工作流',
      'write_task': '写任务',
      'submit_task': '下发',
      'which_workflow': '落到哪个工作流',
      'click_to_select': '点击选择',
      'task_content': '任务内容',
      'task_placeholder': '例如：两周内上线可用 MVP，并完成首批用户验证。',
      'priority': '优先级',
      'priority_low': '低',
      'priority_mid': '中',
      'priority_high': '高',
      'clear': '清空',
      'tips': '小贴士',
      'no_workflow_tip': '还没有工作流？先到「项目」创建一个，再回到本页选择并下发。',
      'add_select_project': '选择项目',
      'add_picker_new_project': '＋ 新建项目',
      'add_new_project_title': '新建项目',
      'add_new_project_name_ph': '项目名称（必选）',
      'add_new_project_desc_ph': '项目说明（可选）',
      'create_project': '创建项目',
      'no_projects_yet': '还没有项目',
      'no_projects_desc': '点右上角「创建项目」，或下面按钮开始。',
      'please_enter_project_name': '请输入项目名称',
      'add_new_project_success': '项目已创建',
      'add_new_project_create_failed': '创建失败，请重试',
      'add_new_project_id_missing': '已创建，请在项目列表中重新选择',
      'open_project': '打开项目',
      'boss_dashboard': '老板指令台',
      'boss_dashboard_sub': '选择模板并确认流向，用一句话下达可执行任务',
      'instruction_flow': '指令流向',
      'source_dept': '来源部门',
      'target_dept': '目标部门',
      'task_goal': '任务目标（老板口吻）',
      'dispatch_preview': '下发预览',
      'operator_label': '发起人',
      'boss_fallback': '老板',
      'flow_preview': '流向',
      'priority_preview': '优先级',
      'input_task_hint': '请在上方输入任务目标，建议包含结果、时间、验收标准。',
      'message': '消息',
      'conversation': '会话',
      'collaboration': '协作与部门',
      'conversation_tip': '经理总览、项目群与工作流会话',
      'department_tip': '按部门浏览岗位角色，进入人格对话',
      'loading': '加载中...',
      'no_conversation': '暂无会话',
      'create_group_agent': '点击右上角「＋」创建项目群或数字员工',
      'create_project_group': '创建项目群',
      'create_digital_employee': '创建数字员工',
      'add_department': '添加部门',
      'remove_department': '删除部门',
      'dept_name_placeholder': '请输入部门名称',
      'added': '已添加',
      'deleted': '已删除',
      'confirm_add': '确认添加',
      'add_role': '添加员工',
      'remove_role': '删除员工',
      'no_role_to_add': '暂无可添加的员工',
      'no_department': '暂无部门',
      'no_department_to_add': '暂无可添加的部门',
      'welcome_back': '欢迎回来',
      'login_subtitle': '使用账号或手机号登录，开始使用工作台',
      'account_phone': '账号 / 手机号',
      'input_account_phone': '请输入账号或手机号',
      'password': '密码',
      'input_password': '请输入密码',
      'login': '登录',
      'logging_in': '登录中…',
      'no_account': '还没有账号？注册',
      'please_input_phone': '请输入手机号',
      'please_input_password': '请输入密码',
      'login_success_no_token': '登录成功但未返回 token',
      'login_success': '登录成功',
      'create_account': '创建账号',
      'register_subtitle': '手机号注册；验证码用于防止机器批量注册（本地图形校验）',
      'phone': '手机号',
      'input_phone': '请输入手机号',
      'verification_code': '验证码',
      'input_captcha': '请输入图中数字',
      'captcha_refresh': '看不清？点击图片刷新',
      'password_min_length': '至少 6 位',
      'confirm_password': '确认密码',
      'input_confirm_password': '再次输入密码',
      'register': '注册',
      'have_account': '已有账号？去登录',
      'captcha_error': '验证码错误',
      'passwords_not_match': '两次密码不一致',
      'register_success': '注册成功',
      'register_success_login': '注册成功，请登录',
      'workbench': '工作台',
      'tasks': '任务',
      'communication': '沟通',
      'graph': '图谱',
      'feed': '动态',
      'by_department': '按部门',
      'kanban': '看板',
      'list': '列表',
      'issue_command': '下发指令',
      'internal': '内部',
      'customer': '客户',
      'initialize_thread': '初始化线程',
      'broadcast': '播报',
      'select_thread_or_initialize': '请选择左侧线程或先初始化',
      'refresh_graph': '刷新图谱',
      'no_node_data': '暂无节点数据',
      'relationship_edges': '关系边',
      'refresh_feed': '刷新动态',
      'no_events': '暂无事件（或接口未开放）',
      'source_department': '来源部门',
      'target_department': '目标部门',
      'hierarchy_level': '层级',
      'command_body_required': '指令正文（必填）',
      'generate_task_title_optional': '生成任务标题（可选）',
      'parent_task': '父任务',
      'dependent_task': '依赖任务',
      'submit': '提交',
      'update_progress': '更新进度',
      'remark_optional': '备注（可选）',
      'save': '保存',
      'saving': '保存中…',
      'command_broadcast': '指令播报',
      'title_optional': '标题（可选）',
      'broadcast_content': '播报内容',
      'send': '发送',
      'message_link_task': '消息关联任务',
      'confirm': '确定',
      'not_started': '未开始',
      'in_progress': '进行中',
      'blocked': '阻塞',
      'done': '完成',
      'unknown': '未知',
      'unnamed_task': '未命名任务',
      'unnamed_workflow': '未命名工作流',
      'workflow_chat_title': '工作流沟通',
      'workflow_thread_hero': '工作流沟通线程',
      'workflow_id_prefix': '工作流编号：',
      'workflow_remote_storage_tip': '工作流会话正文在服务端保存；本页清空仅影响本机已拉取列表的展示缓存。',
      'thread_default': '线程',
      'comms_no_message': '（暂无消息）',
      'comms_load_failed': '（加载失败）',
      'modal_need_workflow_first': '需要先在「项目」里创建工作流，是否前往？',
      'modal_pick_workflow_hint': '请先到「项目」里创建并进入过一次，或点「选择」从列表里指定。',
      'go_to_project': '去项目',
      'action_select': '选择',
      'please_write_task_content': '请先写任务内容',
      'please_enter_workflow_name': '请输入名称',
      'task_pick_none': '（无）',
      'chat_title_fallback': '聊天',
      'chat_settings_title': '聊天信息',
      'unassigned': '未分配',
      'from_task': '来自任务',
      'to_task': '→ 任务',
      'link_task': '关联任务',
      'please_enter_command_body': '请填写指令正文',
      'please_select_department': '请选择部门',
      'issued': '已下发',
      'updated': '已更新',
      'sent': '已发送',
      'broadcasted': '已播报',
      'linked': '已关联',
      'please_select_thread': '请选择线程',
      'please_enter_content': '请输入内容',
      'please_enter_broadcast_content': '请输入播报内容',
      'please_select_task': '请选择任务',
      'missing_workflow_id': '缺少工作流 ID',
      'bootstrap_requested': '已请求初始化',
      'basic_info': '基本信息',
      'group_name': '群名称',
      'group_name_placeholder': '例如：某某客户 · 交付群',
      'client_project_shortname': '客户 / 项目简称',
      'client_project_placeholder': '方便在列表里一眼识别',
      'deliverable_description': '交付物说明',
      'deliverable_placeholder': '例如：小程序商城 + 管理后台；验收标准、关键里程碑等',
      'plan_reminder': '计划与提醒',
      'expected_delivery_date': '期望上线 / 交付日',
      'select_date_optional': '选择日期（可选）',
      'daily_report_reminder_time': '群内日报提醒时间',
      'daily_report_reminder_hint': '创建后，员工将在此时间前后提交日报（演示）',
      'other': '其他',
      'remarks': '备注',
      'remarks_placeholder': '项目背景、客户对接人、沟通禁忌等',
      'create_project_group': '创建项目群',
      'please_enter_group_name': '请填写群名称',
      'created': '已创建',
      'identity_role': '身份与角色',
      'name_title': '称呼',
      'name_placeholder': '例如：小艾、阿强、陈经理',
      'position_responsibility': '岗位 / 职责',
      'position_placeholder': '例如：项目经理、前端、后端、运维、测试',
      'gender_display': '性别（展示用）',
      'gender_option_private': '保密',
      'gender_option_male': '男',
      'gender_option_female': '女',
      'reply_option_brief': '简洁',
      'reply_option_detailed': '详细',
      'reply_option_bluf': '先说结论再展开',
      'personality_experience': '人设与经历',
      'personality_keywords': '性格关键词',
      'personality_placeholder': '例如：稳重、偏细节、沟通直接',
      'hobbies_catchphrases': '爱好 / 口头禅（可选）',
      'hobbies_placeholder': '用于让对话更自然',
      'project_experience_summary': '项目经历摘要',
      'experience_placeholder': '例如：做过 3 个电商小程序、熟悉支付与订单',
      'collaboration_preference': '协作偏好',
      'reply_style': '回复风格',
      'reply_style_hint': '后续对接 AI 时，将优先按此风格生成回复与日报。',
      'additional_notes': '补充说明',
      'additional_notes_placeholder': '对老板的工作习惯、禁忌、对接方式等',
      'agent_creation_note': '创建后为本地数字员工；可一键「裁员」停用（后续版本）。',
      'create_digital_agent': '创建数字员工',
      'please_enter_name': '请填写称呼',
      'please_enter_position': '请填写岗位',
      'change': '更换',
      'nickname': '昵称',
      'please_enter_nickname': '请输入昵称',
      'phone_number': '手机号',
      'save_nickname': '保存昵称',
      'nickname_max_20': '昵称最多 20 字',
      'saved': '已保存',
      'change_password': '修改密码',
      'change_password_hint': '修改成功后请牢记新密码；接口需登录态。',
      'current_password': '当前密码',
      'please_enter_current_password': '请输入当前密码',
      'new_password': '新密码',
      'new_password_min_6': '至少 6 位',
      'confirm_new_password': '确认新密码',
      'reenter_new_password': '再次输入新密码',
      'save_new_password': '保存新密码',
      'please_login_first': '请先登录',
      'current_password_error': '当前密码错误',
      'cannot_use_same_password': '不能修改与当前一样的密码',
      'change_failed_retry': '修改失败，请稍后重试',
      'change_success': '修改成功',
      'department_not_found': '未找到该部门',
      'missing_department_id': '缺少部门 ID',
      'settings_section_account': '账号与安全',
      'settings_section_preferences': '偏好设置',
      'settings_section_privacy': '隐私设置',
      'settings_section_general': '通用设置',
      'settings_font_size': '字体大小',
      'settings_dark_mode': '深色模式',
      'settings_read_receipt': '消息已读回执',
      'settings_read_receipt_sub': '关闭后对方不会看到你是否阅读消息',
      'settings_online_status': '在线状态',
      'settings_online_status_sub': '显示你的在线或离线状态',
      'settings_privacy_policy': '隐私政策',
      'settings_export_data': '数据导出',
      'settings_check_update': '检查更新',
      'settings_version_sub': '当前版本 {{ver}}',
      'settings_clear_cache': '清理缓存',
      'settings_clear_cache_sub': '当前缓存：{{size}}',
      'modal_clear_cache_title': '清理缓存',
      'modal_clear_cache_body': '确定要清理缓存吗？当前缓存大小：{{size}}',
      'action_clear_cache': '清理',
      'toast_clear_cache_ok': '清理成功',
      'toast_clear_cache_fail': '清理失败',
      'modal_export_data_title': '数据导出',
      'modal_export_data_body': '将本地数字员工、项目群、工作流等配置复制为 JSON（推荐先复制到备忘录备份）。',
      'action_copy_json': '复制 JSON',
      'export_data_json_label': '一人公司数据',
      'toast_clipboard_ok': '已复制到剪贴板',
      'toast_clipboard_fail': '复制失败',
      'toast_export_fail': '导出失败',
      'loading_check_update': '检查中…',
      'modal_check_update_title': '检查更新',
      'modal_check_update_body': '当前已是最新版本 ({{ver}})',
      'action_got_it': '我知道了',
      'toast_font_changed': '字体已调整为 {{size}}',
      'toast_dark_on': '已开启深色模式',
      'toast_dark_off': '已关闭深色模式',
      'toast_read_receipt_on': '已开启已读回执',
      'toast_read_receipt_off': '已关闭已读回执',
      'toast_online_on': '已显示在线状态',
      'toast_online_off': '已隐藏在线状态',
      'modal_privacy_policy_title': '隐私政策',
      'modal_privacy_policy_body': '我们尊重并保护您的个人隐私。您的数据将仅用于改善服务体验，不会被未经授权的第三方访问。',
      'cache_size_unknown': '未知',
      'language_name_zh': '简体中文',
      'language_name_en': 'English',
      'toast_language_zh': '已切换为简体中文',
      'toast_language_en': 'Switched to English',
      'font_size_xs': '小',
      'font_size_sm': '中',
      'font_size_md': '大',
      'font_size_xl': '特大',
      'profile_quick_hire_title': '招聘新员工',
      'profile_quick_hire_sub': '添加 AI 数字员工',
      'profile_quick_group_title': '创建项目群',
      'profile_quick_group_sub': '新建协作项目空间',
      'profile_daily_report': '工作日报',
      'profile_daily_report_sub': '查看团队今日工作',
      'profile_assign_task': '下发任务',
      'profile_assign_task_sub': '指派工作给 AI 团队',
      'profile_about_tagline': '一人公司 · AI 驱动',
      'profile_about_sub': '你当老板，AI 当员工',
      'profile_popup_my_team': '我的团队',
      'profile_team_count': '{{count}} 位员工',
      'profile_agents_empty': '还没有数字员工',
      'profile_agents_empty_sub': '点击「招聘新员工」创建你的第一位 AI 员工',
      'profile_hire_new_cta': '＋ 招聘新员工',
      'profile_report_team_status': '团队状态',
      'profile_report_no_agents': '暂无数字员工',
      'agent_status_busy': '忙碌中',
      'agent_status_ready': '已就绪',
      'account_sub_guest': '点击登录，开始管理你的 AI 团队',
      'account_sub_logged': '一人公司 · 团队负责人',
      'profile_report_date': '{{y}}年{{m}}月{{d}}日',
      'profile_agent_char_fallback': '员',
      'settings_switch_logout_hint': '切换账号将前往登录页以使用其他账号；退出账号将清除本机登录状态并返回「我的」。',
      'language_settings': '语言设置',
      'switch_account_modal_body': '将退出当前账号并前往登录页，以便使用其他账号登录。',
      'go_to_login': '前往登录',
      'logout_confirm_body': '确定退出当前账号吗？',
      'logout_action': '退出',
      'logged_out': '已退出',
      'language_switched': '语言已切换',
      'nav_back': '返回',
      'profile_avatar_guest': '用',
      'profile_avatar_me': '我',
      'my_profile_default': '我的资料',
      'profile_info_nav': '个人资料',
      'please_complete_phone': '请完善手机号',
      'uploading': '上传中',
      'avatar_updated': '头像已更新',
      'model_settings_tip': '密钥仅保存在本机。保存时会校验接口是否可用（先请求 models，不支持时再发一条最小聊天）。对话时直接向「接口地址」发起聊天补全（OpenAI 兼容）。微信小程序需在公众平台配置该域名为合法 request 域名；或使用与后端同域的代理。',
      'model_settings_tip_title': '安全说明',
      'model_section_connection': '连接',
      'model_section_model': '模型',
      'model_label_api_key': 'API Key',
      'model_label_base_url': '接口根地址（含 /v1）',
      'model_label_model_name': '模型名',
      'model_placeholder_key': 'sk-… 或服务商密钥',
      'model_validate_key_required': '请填写 API Key',
      'model_validate_url_required': '请填写接口根地址',
      'model_validate_url_invalid': '接口地址格式不正确，需为有效的 http(s) 链接',
      'model_validate_url_protocol': '接口地址仅支持 http 或 https',
      'model_validate_url_need_v1': '路径须以 /v1 结尾（如 https://api.openai.com/v1）',
      'model_validate_model_required': '请填写模型名',
      'model_validate_model_too_long': '模型名过长（最多 128 个字符）',
      'model_verify_loading': '正在验证连接…',
      'model_verify_auth_failed': '密钥无效或无权访问',
      'model_verify_chat_failed': '聊天接口拒绝请求',
      'model_verify_http': '接口返回错误',
      'model_verify_network': '网络异常或服务不可达',
      'model_verify_failed': '连接验证失败',
      'staff_api_nav': '员工与模型',
      'staff_api_tip_title': '说明',
      'staff_api_tip': '在此添加常用模型名称（如 gpt-4o-mini）。保存后可在「员工与模型」中从列表选择，无需每次手打。',
      'staff_api_section_add': '添加模型名',
      'staff_api_section_list': '已保存的模型',
      'staff_api_add_placeholder': '输入模型 ID 或名称',
      'staff_api_add_btn': '添加',
      'staff_api_empty': '暂无模型。请在上方输入并添加。',
      'staff_api_empty_name': '请输入模型名称',
      'staff_api_remove': '删除',
      'staff_api_remove_title': '删除模型',
      'staff_api_remove_body': '确定从列表中移除「{{name}}」？不影响已分配给员工的设置。',
      'staff_api_added': '已添加',
      'staff_api_removed': '已删除',
      'agent_model_pick_from_list': '从列表选择',
      'agent_model_assign_nav': '员工与模型',
      'agent_model_assign_tip_title': '说明',
      'agent_model_assign_tip':
        '请先点击「添加模型」完成连接与校验并加入可选列表；在下方轻触员工姓名即可选择模型，选择后自动保存。',
      'agent_model_add_model_btn': '添加模型',
      'agent_model_added_to_list': '已添加',
      'agent_model_api_already_added': '已添加过该模型',
      'agent_model_name_exists': '已存在该名称',
      'agent_model_view_models_btn': '查看模型',
      'agent_model_detail_title': '模型详情',
      'agent_model_view_empty': '暂无已添加的模型',
      'agent_model_field_empty': '未填写',
      'agent_model_delete_saved': '删除此模型',
      'agent_model_delete_saved_title': '删除模型',
      'agent_model_delete_saved_body': '确定删除「{{name}}」？删除后仍可在「添加模型」中重新添加。',
      'agent_model_deleted': '已删除',
      'agent_model_confirm_delete': '确认删除',
      'agent_model_delete_failed': '删除失败，请重试',
      'agent_model_staff_list_title': '员工列表',
      'agent_model_section_staff': '分配给数字员工',
      'agent_model_batch_placeholder': '批量：输入模型名',
      'agent_model_apply_batch': '应用到选中',
      'agent_model_select_all': '全选',
      'agent_model_save_all': '保存全部',
      'agent_model_save_one': '保存本条',
      'agent_model_saved': '已保存',
      'agent_model_empty': '暂无数字员工。请在「消息」页右上角创建数字员工后再来分配模型。',
      'agent_model_row_placeholder': '请选择模型',
      'agent_model_none_selected': '请先勾选要批量设置的员工',
      'agent_model_batch_applied': '已为 {{count}} 名员工设置模型',
      'agent_llm_system_prompt': '你是团队中的数字员工「{{name}}」，岗位：{{role}}。请用简洁、专业的口吻回复用户，保持角色一致。',
      'chat_search_nav': '查找聊天记录',
      'chat_search_placeholder': '搜索聊天内容',
      'chat_search_no_hits': '未找到相关内容',
      'chat_search_hint': '输入关键词搜索',
      'load_failed_short': '加载失败',
      'time_yesterday': '昨天',
      'date_month_day': '{{month}}月{{day}}日',
      'role_count_suffix': '岗',
      'manager_overview_title': '经理总览',
      'digital_employee_fallback': '数字员工',
      'project_group_fallback': '项目群',
      'abbr_manager': '经',
      'abbr_group': '群',
      'abbr_project': '项',
      'abbr_staff': '员',
      'sender_system': '系统',
      'manager_feed_keyword': '经理总览',
      'home_sender_me': '我',
      'chat_no_messages': '暂无消息',
      'feed_badge_must_read': '主读',
      'vt_demo_group_mall_name': '示例 · 商城小程序项目群',
      'vt_demo_group_mall_desc': '客户 A 交付群',
      'vt_demo_agent_chen_name': '陈经理',
      'vt_demo_agent_xiao_name': '小艾',
      'vt_demo_agent_qiang_name': '阿强',
      'role_title_pm': '项目经理',
      'role_title_frontend': '前端',
      'role_title_backend': '后端',
      'vt_unnamed_group': '未命名项目群',
      'vt_default_agent_name': '数字员工',
      'vt_member_default': '成员',
      'vt_preview_me_prefix': '我：',
      'vt_group_created_toast': '群已创建，开始协作吧',
      'vt_demo_group_last_preview': '项目经理：本周联调窗口已对齐',
      'vt_demo_agent1_last_preview': '明日站会提前到 10:00',
      'vt_demo_agent2_last_preview': '首页骨架屏已提交',
      'vt_demo_agent3_last_preview': '订单接口 Swagger 已更新',
      'hall_welcome_body':
        '欢迎加入【公司全员群】。每日 21:00 各数字员工在此提交日报，21:30 经理推送总览。您可随时 @ 员工安排工作。',
      'hall_digest_start': '—— 今日 21:00 日报开始 ——',
      'hall_daily_prefix': '【日报】',
      'agent_chat_seed_body': '你好，我是{{name}}（{{role}}）。下面是我的今日日报摘要。\n{{summary}}',
      'agent_seed_role_fallback': '岗位',
      'agent_seed_ready_line': '【{{role}}】已就绪，听候安排。',
      'seed_inbox_title': '问候',
      'seed_inbox_question': '有什么问题',
      'vt_agent_ready_hint': '已就绪，随时听候安排',
      'briefing_schedule_note': '每日 21:00 各员工自动提交日报，21:30 经理生成总览',
      'briefing_time_2100': '今日 21:00',
      'briefing_time_2130': '今日 21:30',
      'briefing_employee_summary': '【{{role}}】今日完成例行推进；风险：无阻塞；明日：继续当前迭代。',
      'briefing_manager_summary': '【经理总览】今日整体进度正常。重点：客户侧验收清单已对齐；明日优先联调支付链路。{{schedule}}',
      'vt_hall_sender_1': '陈经理（项目经理）',
      'vt_hall_sender_2': '小艾（前端）',
      'vt_hall_sender_3': '阿强（后端）',
      'chat_input_placeholder': '输入消息...',
      'chat_requesting': '请求中…',
      'multi_cancel': '取消',
      'multi_selected': '已选 {{count}} 条',
      'action_copy': '复制',
      'action_forward': '转发',
      'action_delete': '删除',
      'toast_copied': '已复制',
      'toast_copied_paste': '已复制，可粘贴到其他会话',
      'toast_select_msg_first': '请先选择消息',
      'toast_copied_merge': '已复制合并内容，可粘贴到其他会话',
      'toast_remote_no_delete': '远程会话暂不支持删除',
      'delete_messages_title': '删除消息',
      'delete_messages_body': '将删除已选的 {{count}} 条消息（仅本机）',
      'toast_remote_no_recall': '远程消息暂不支持撤回',
      'toast_recalled': '已撤回',
      'toast_remote_cannot_delete': '远程消息无法删除',
      'delete_one_title': '删除消息',
      'delete_one_body': '从本机删除该条消息？',
      'menu_copy': '复制',
      'menu_recall': '撤回',
      'menu_delete': '删除',
      'menu_forward': '转发',
      'menu_multiselect': '多选',
      'message_empty_mark': '（空）',
      'toast_set_api_key_in_profile': '请先在「我的 → 员工与模型」填写密钥',
      'toast_agent_content_missing': '未获取到人设正文，请确认后端 /api/agents 可用',
      'assistant_name_short': '助手',
      'model_err_title': '模型请求失败，请检查密钥与合法域名',
      'model_err_body': '（模型调用失败：请检查密钥、接口地址，且小程序需配置 request 合法域名）',
      'sender_system_name': '系统',
      'chat_list_title': '消息',
      'boss_chat_name': '老板',
      'engineering_department': '工程部',
      'reply_ok_title': '回复',
      'reply_ok_content': '好的，我知道了',
      'workbench_id_label': 'ID：',
      'wb_from_dept': '发件部门：',
      'wb_to_dept': '收件部门：',
      'wb_link_from_task': '关联来源任务：',
      'wb_link_to_task': '关联目标任务：',
      'wb_msg_placeholder': '输入消息内容',
      'wb_optional_paren': '（可选）',
      'wb_parent_prefix': '父任务',
      'wb_dep_prefix': '依赖',
      'wb_task_prefix': '任务 {{id}}',
      'wb_node_fallback': '节点',
      'tab_switch_failed': '切换失败',
      'dept_roles_empty': '暂无该部门下的角色',
      'dept_roles_empty_hint': '请确认本地人设表已包含该部门分类；下拉刷新重试。',
      'dept_roles_hero_title': '可选角色',
      'dept_roles_hero_meta': '共 {{count}} 位 · 轻触进入对话',
      'dept_roles_nav': '岗位角色',
      'cs_no_desc': '暂无简介',
      'cs_client_prefix': '客户：',
      'cs_delivery_prefix': '交付：',
      'cs_digital_employee_role': '数字员工',
      'cs_one_on_one': '一对一工作沟通',
      'cs_hq_desc': '全员大群 · 日报与经理总览',
      'cs_manager_desc': '每日 21:30 推送总览 · 可与系统留痕沟通',
      'cs_persona_desc': '人格对话 · 本地演示（未接大模型）',
      'cs_local_session': '本地会话',
      'cs_find_chat_history': '查找聊天记录',
      'cs_group_manage': '群管理',
      'cs_group_notice': '群公告',
      'cs_pin_chat': '置顶聊天',
      'cs_mute': '消息免打扰',
      'cs_clear_history': '清空聊天记录',
      'cs_hq_members_modal': '全员群 · 共 {{count}} 位数字员工',
      'cs_no_members': '暂无成员',
      'cs_collab_members_plain': '协作成员',
      'cs_collab_members_named': '「{{name}}」协作成员',
      'cs_notice_hq_body': '每日 21:00 各员工提交日报，21:30 经理总览推送至本群。',
      'cs_notice_empty': '暂无群公告。可在「创建项目群」时填写项目说明，或后续在管理后台维护。',
      'cs_clear_modal_title': '清空聊天记录',
      'cs_clear_modal_body': '将删除本机该会话的聊天内容，是否继续？',
      'cs_cleared_remote_cache': '已清除本机展示缓存',
      'cs_cleared': '已清空',
      'cs_no_message_stub': '暂无消息',
      'dept_def_goal': '目标',
      'dept_def_goal_ph': '描述本阶段要达成的结果',
      'dept_def_priority': '优先级',
      'dept_def_roles': '角色（多选）',
      'dept_def_submit': '生成任务草稿',
      'dept_def_err_goal': '请填写目标',
      'dept_def_err_role': '请选择角色',
      'dept_def_ok': '草稿已生成（待接后端）',
      'dept_eng_err_goal': '请填写迭代目标',
      'dept_eng_err_peer': '请至少编入一名队友',
      'dept_eng_ok': '迭代单已生成（待接后端）',
      'dept_eng_eyebrow': '研发交付',
      'dept_eng_sprint_h': '本迭代目标',
      'dept_eng_sprint_ph': '要交付的范围、口径与截止时间',
      'dept_eng_debt_h': '技术债快记',
      'dept_eng_debt_ph': '简述一项技术债…',
      'dept_eng_debt_add': '追加',
      'dept_eng_debt_del': '删',
      'dept_eng_debt_empty': '暂无记录，迭代评审时可一并过一遍。',
      'dept_eng_release_h': '计划发布窗口',
      'dept_eng_release_slot_0': '本周四晚窗口',
      'dept_eng_release_slot_1': '周五午间窗口',
      'dept_eng_release_slot_2': '下周一灰度',
      'dept_eng_release_slot_3': '待定 / 跟随版本火车',
      'dept_eng_squad_h': '编入交付小队',
      'dept_eng_squad_sub': '点选成员（可多选）',
      'dept_eng_reset': '清空',
      'dept_eng_submit': '生成迭代单',
      'dept_sup_err_body': '请填写诉求摘要',
      'dept_sup_err_skill': '请选择指派能力',
      'dept_sup_ok': '支援单已创建（待接后端）',
      'dept_spe_err_brief': '请填写任务综述',
      'dept_spe_err_step': '请至少填写一步编排',
      'dept_spe_err_expert': '请选择专家角色',
      'dept_spe_ok': '编排方案已生成（待接后端）',
      'dept_spe_eyebrow': '跨域编排',
      'dept_spe_brief_h': '任务综述',
      'dept_spe_brief_ph': '涉及哪些系统、代理、合规边界，期望的最终产物形态',
      'dept_spe_mcp_h': '启用 MCP 工具扩展',
      'dept_spe_steps_h': '编排步骤（有序）',
      'dept_spe_step_ph': '步骤说明',
      'dept_spe_step_add': '＋ 步骤',
      'dept_spe_pool_h': '专家池（多选）',
      'dept_spe_reset': '重置',
      'dept_spe_submit': '生成编排方案',
      'dept_sal_err_name': '请填写机会名称',
      'dept_sal_err_role': '请选择销售角色',
      'dept_sal_ok': '赢单草稿已保存（待接后端）',
      'dept_mkt_err_theme': '请填写战役主题',
      'dept_mkt_err_role': '请至少选择一名角色',
      'dept_mkt_ok': '简报已生成（待接后端）',
      'dept_mkt_eyebrow': '增长与传播',
      'dept_mkt_campaign_h': '战役代号 / 主题',
      'dept_mkt_campaign_ph': '例如：新品上市 · 第二波认知',
      'dept_mkt_matrix_h': '渠道矩阵（触达）',
      'dept_mkt_mx_douyin': '短视频',
      'dept_mkt_mx_wx': '微信生态',
      'dept_mkt_mx_seo': '搜索/SEO',
      'dept_mkt_mx_kol': '达人',
      'dept_mkt_mv_on': '主推',
      'dept_mkt_mv_off': '待定',
      'dept_mkt_brief_h': '核心信息与素材诉求',
      'dept_mkt_brief_ph': '一句话主张、三条证据、要的素材规格',
      'dept_mkt_team_h': '编组（可多选）',
      'dept_mkt_reset': '重置',
      'dept_mkt_submit': '生成战役简报',
      'dept_prd_eyebrow': '产品与路线',
      'dept_prd_box_h': '当前时间盒',
      'dept_prd_box_0': '本周',
      'dept_prd_box_1': '本月',
      'dept_prd_box_2': '本季度',
      'dept_prd_box_3': '下季度',
      'dept_prd_hypo_h': '正在验证的假设',
      'dept_prd_hypo_ph': '可衡量的用户行为或业务信号，例如：企业版权限模型的付费转化率',
      'dept_prd_focus_h': '焦点模式',
      'dept_prd_mode_discovery': '发现',
      'dept_prd_mode_delivery': '交付',
      'dept_prd_team_h': '产品经理编组（多选）',
      'dept_prd_reset': '清空',
      'dept_prd_submit': '生成路线评估',
      'dept_pm_eyebrow': '交付治理',
      'dept_pm_ms_h': '里程碑 / 检查点',
      'dept_pm_ms_ph': '描述节点与完成标准',
      'dept_pm_ms_del': '删',
      'dept_pm_ms_add': '＋ 添加节点',
      'dept_pm_risk_h': '综合风险热度（自评 1–5）',
      'dept_pm_gov_h': '启用治理角色',
      'dept_pm_reset': '清空',
      'dept_pm_submit': '导出治理纪要',
      'dept_prd_err_hypo': '请填写假设',
      'dept_prd_err_pm': '请选择 PM 角色',
      'dept_prd_ok': '路线图切片已生成（待接后端）',
      'dept_pm_err_milestone': '请填写至少一个里程碑',
      'dept_pm_err_gov': '请选择治理角色',
      'dept_pm_ok': '纪要草稿已生成（待接后端）',
      'dept_paid_err_kpi': '请填写 KPI 方向',
      'dept_paid_err_role': '请勾选协同角色',
      'dept_paid_ok': '投放单已生成（待接后端）',
      'dept_paid_eyebrow': '投放与效果',
      'dept_paid_pace_h': '预算节拍（自评）',
      'dept_paid_pace_hint': '用于对齐「是否该加码/收量」，不接真实账户也可先填主观节奏。',
      'dept_paid_channels_h': '启用渠道',
      'dept_paid_ch_search': '搜索',
      'dept_paid_ch_social': '信息流',
      'dept_paid_ch_shop': '电商',
      'dept_paid_kpi_h': '投放目标 / KPI',
      'dept_paid_kpi_ph': '例如：CPA ↓12%，再营销列表扩充至 5 万设备',
      'dept_paid_roles_h': '协同角色',
      'dept_paid_reset': '重置',
      'dept_paid_submit': '生成投放动作单',
      'dept_sal_eyebrow': '商机管道',
      'dept_sal_stage_h': '当前阶段',
      'dept_sal_stage_disc': '发现',
      'dept_sal_stage_qual': '验证',
      'dept_sal_stage_prop': '方案',
      'dept_sal_stage_close': '收尾',
      'dept_sal_deal_h': '机会名称',
      'dept_sal_deal_ph': '例如：某集团年度框架谈判',
      'dept_sal_next_h': '下一步 / 阻挡点',
      'dept_sal_next_ph': '要写清下一步会议、材料、或竞品动态',
      'dept_sal_skill_h': '请哪类销售能力介入',
      'dept_sal_reset': '清空',
      'dept_sal_submit': '同步赢单草稿',
      'dept_sup_eyebrow': '客户与内部支援',
      'dept_sup_type_h': '工单类型',
      'dept_sup_type_0': '功能咨询',
      'dept_sup_type_1': '故障 / 不可用',
      'dept_sup_type_2': '账单与合规',
      'dept_sup_type_3': '数据与报表',
      'dept_sup_sla_h': '响应 SLA',
      'dept_sup_sla_std_l': '标准',
      'dept_sup_sla_std_d': '工作日队列',
      'dept_sup_sla_urg_l': '紧急',
      'dept_sup_sla_urg_d': '升级与值班',
      'dept_sup_body_h': '诉求摘要',
      'dept_sup_body_ph': '现象、影响面、已尝试操作、期望恢复时间',
      'dept_sup_assign_h': '指派能力',
      'dept_sup_reset': '重置',
      'dept_sup_submit': '创建支援单',
      'dept_fin_err_ask': '请填写诉求说明',
      'dept_fin_err_role': '请选择财务角色',
      'dept_fin_ok': '财务作业已发起（待接后端）',
      'dept_fin_eyebrow': '财务纪律',
      'dept_fin_period_h': '会计期间',
      'dept_fin_period_ph': '选择年月',
      'dept_fin_job_h': '本次作业类型',
      'dept_fin_job_close_l': '月结',
      'dept_fin_job_close_h': '结账与报表',
      'dept_fin_job_fpa_l': '预测',
      'dept_fin_job_fpa_h': '滚动预测/经营分析',
      'dept_fin_job_tax_l': '税务',
      'dept_fin_job_tax_h': '筹划与合规',
      'dept_fin_ask_h': '诉求说明',
      'dept_fin_ask_ph': '需出具的报表、波动归因、税务假设或内控关注点',
      'dept_fin_role_h': '财务职能参与',
      'dept_fin_reset': '重置',
      'dept_fin_submit': '发起财务作业',
      'dept_des_err_deliver': '请勾选至少一项交付物',
      'dept_des_err_seat': '请选定一个主设计席位',
      'dept_des_ok': '设计工单已生成（待接后端）',
      'dept_des_eyebrow': '体验与视觉',
      'dept_des_track_h': '课题轨道',
      'dept_des_track_ui': '界面',
      'dept_des_track_ux': '用研',
      'dept_des_track_system': '系统',
      'dept_des_deliver_h': '本轮交付物',
      'dept_des_del_hifi': '高保真关键页面',
      'dept_des_del_empty': '空状态 / 错误态',
      'dept_des_del_ds': '组件库增量',
      'dept_des_a11y_h': '无障碍审计',
      'dept_des_notes_h': '备注 / 约束',
      'dept_des_notes_ph': '品牌边界、像素规则、交互动效上限等',
      'dept_des_seat_h': '席位（选角色）',
      'dept_des_reset': '重置',
      'dept_des_submit': '生成设计工单',
      'dept_qa_err_scope': '请填写验证范围',
      'dept_qa_err_severity': '请选择严重级别',
      'dept_qa_err_role': '请选择测试角色',
      'dept_qa_ok': '验证单已出具（待接后端）',
      'dept_qa_eyebrow': '质量门禁',
      'dept_qa_scope_h': '验证范围',
      'dept_qa_scope_ph': '链路、接口、浏览器矩阵、回归集名称…',
      'dept_qa_sev_h': '关注严重级别（多选）',
      'dept_qa_env_h': '验证环境',
      'dept_qa_env_0': '开发',
      'dept_qa_env_1': '预发 / Staging',
      'dept_qa_env_2': '生产只读镜像',
      'dept_qa_env_3': '生产（受控窗口）',
      'dept_qa_team_h': '测试编组',
      'dept_qa_reset': '重置',
      'dept_qa_submit': '出具验证单',
      'dept_spa_err_goal': '请填写体验目标',
      'dept_spa_err_team': '请选择技术编组',
      'dept_spa_ok': '空间交付单已生成（待接后端）',
      'dept_spa_eyebrow': '空间体验',
      'dept_spa_fps_h': '目标帧体验（FPS 档位）',
      'dept_spa_tier_h': '场景复杂度',
      'dept_spa_tier_low': '轻量',
      'dept_spa_tier_mid': '中等',
      'dept_spa_tier_high': '重度',
      'dept_spa_goal_h': '体验与性能目标',
      'dept_spa_goal_ph': '晕眩控制、手势时延、定位容差、多用户同步等',
      'dept_spa_team_h': '空间技术编组',
      'dept_spa_reset': '清空',
      'dept_spa_submit': '生成空间交付单',
      'dept_aca_err_task': '请填写论证任务',
      'dept_aca_err_lead': '请选择首席学者',
      'dept_aca_ok': '任务书已生成（待接后端）',
      'dept_aca_eyebrow': '叙事与世界观',
      'dept_aca_disc_h': '学科视角',
      'dept_aca_disc_anthro': '人类学',
      'dept_aca_disc_hist': '历史',
      'dept_aca_disc_psych': '心理',
      'dept_aca_disc_hint': '视角决定提问方式；下方学者列表与数据一致，用于强调当前论证主线。',
      'dept_aca_task_h': '论证 / 设定任务',
      'dept_aca_task_ph': '要澄清的矛盾、需要考证的史实或人物动机线索',
      'dept_aca_lead_h': '首席学者（单选）',
      'dept_aca_reset': '重置',
      'dept_aca_submit': '生成学术任务书',
      'agent_drawer_close': '关闭',
      'agent_drawer_expertise': '专业：',
      'agent_drawer_when': '使用时机：',
      'agent_drawer_create_task': '发起任务',
      'err_network': '网络异常，请稍后重试',
      'err_timeout_net': '连接超时：可换网络或稍后重试',
      'err_domain': '请求被拒绝：请配置合法域名或检查网络',
      'err_abort': '请求已中断',
      'err_ssl': '安全连接失败，请稍后重试',
      'err_login_expired': '登录已失效，请重新登录',
      'err_upload_failed': '上传失败',
      'err_request_failed': '请求失败',
      'err_service_unavailable': '服务暂时不可用，请稍后重试',
      'err_404_frontend': '404：请求未到达接口（像打到前端/Nginx）',
      'err_404_double_api': '404：地址里多了一段 /api，请改 .env',
      'err_404_api': '接口404：请对照 Swagger 路径或后端是否部署同一版本',
      // 偏好设置页面
      'preferences_title': '偏好设置',
      'preferences_subtitle': '设置你的公司偏好，让AI员工更好地为你服务',
      'company_industry': '公司行业',
      'industry_tech': '科技',
      'industry_finance': '金融',
      'industry_healthcare': '医疗',
      'industry_education': '教育',
      'industry_retail': '零售',
      'industry_other': '其他',
      'ai_employee_personality': 'AI员工性格',
      'personality_professional': '专业',
      'personality_creative': '创意',
      'personality_friendly': '友好',
      'personality_analytical': '分析',
      'company_size': '公司规模',
      'size_small': '小型',
      'size_medium': '中型',
      'size_large': '大型',
      'business_goals': '业务目标',
      'goal_growth': '增长',
      'goal_innovation': '创新',
      'goal_efficiency': '效率',
      'goal_customer_satisfaction': '客户满意度',
      'continue': '继续',
      'msg_dept_engineering_title': '工程部',
      'msg_dept_engineering_desc': '建设未来，一次承诺一个。',
      'msg_dept_design_title': '设计部',
      'msg_dept_design_desc': '让它变得美丽、实用且令人愉悦。',
      'msg_dept_paid_media_title': '付费媒体部',
      'msg_dept_paid_media_desc': '将广告支出转化为可衡量的业务成果。',
      'msg_dept_sales_title': '销售部',
      'msg_dept_sales_desc': '把管道转化为收入，而不是 CRM 体力活。',
      'msg_dept_marketing_title': '市场部',
      'msg_dept_marketing_desc': '一次一次地真实互动，持续扩大受众。',
      'msg_dept_product_title': '产品部',
      'msg_dept_product_desc': '在正确的时间建造正确的东西。',
      'msg_dept_project_management_title': '项目管理部',
      'msg_dept_project_management_desc': '保持列车准时运行并控制预算。',
      'msg_dept_testing_title': '测试部',
      'msg_dept_testing_desc': '破坏东西，让用户不用再踩坑。',
      'msg_dept_support_title': '支援部',
      'msg_dept_support_desc': '是行动的支柱。',
      'msg_dept_spatial_computing_title': '空间计算部',
      'msg_dept_spatial_computing_desc': '打造沉浸式未来。',
      'msg_dept_specialized_title': '专业部门',
      'msg_dept_specialized_desc': '跨领域专家库，处理高复杂度任务。',
      'msg_dept_finance_title': '财务部',
      'msg_dept_finance_desc': '会计、财务分析、税务和投资研究。',
      'msg_dept_game_development_title': '游戏开发',
      'msg_dept_game_development_desc': '引擎、玩法与工具链，从原型到上线。',
      'msg_dept_academic_title': '学术部',
      'msg_dept_academic_desc': '学术严谨，用于世界构建与叙事设计。'
    },
    en: {
      'home': 'Home',
      'project': 'Project',
      'add': 'Assign Task',
      'message': 'Message',
      'profile': 'Profile',
      'login': 'Login',
      'register': 'Register',
      'settings': 'Settings',
      'language': 'Language',
      'chinese': '简体中文',
      'english': 'English',
      'logout': 'Logout',
      'switch_account': 'Switch Account',
      'model_api': 'Staff & models',
      'change_password': 'Change Password',
      'workflow': 'Workflow',
      'profile_workflow_sub': 'Manage collaborative workflow pipelines',
      'about': 'About',
      'version': 'v1.0',
      'collaboration_workbench': 'Collaboration Workbench · Competition Project',
      'interface_based_on_api': 'Interface based on actual API documentation',
      'not_logged_in': 'Not logged in',
      'click_to_login': 'Account: Click to login',
      'logged_in': 'Account: Logged in',
      'phone': 'Phone: ',
      'my_account': 'My Account',
      'hq_group': 'All Staff Group',
      'hq_subtitle': 'Total {{ count }} digital employees · Daily reports and overviews are sent in this group',
      'loading': 'Loading...',
      'send_message': 'Send message to all staff group...',
      'send': 'Send',
      'project_subtitle': 'Select an existing project to enter the workbench, or create a new collaboration pipeline',
      'count_unit': '',
      'no_workflow': 'No workflows yet',
      'no_workflow_desc': 'After creating a workflow, you can associate it in "Assign Task" or directly enter the workbench to view tasks and communicate.',
      'create_workflow': 'Create Workflow',
      'go_assign_task': 'Go to Assign Task',
      'name_required': 'Name (required)',
      'description_optional': 'Description (optional)',
      'cancel': 'Cancel',
      'create': 'Create',
      'add_subtitle': 'Just write clear goals; by default, it is sent from <text class="em">Product Department</text> to <text class="em">Engineering Department</text>.',
      'select_workflow': 'Select Workflow',
      'write_task': 'Write Task',
      'submit_task': 'Submit',
      'which_workflow': 'Which workflow to use',
      'click_to_select': 'Click to select',
      'task_content': 'Task Content',
      'task_placeholder': 'For example: Launch a usable MVP within two weeks and complete first user verification.',
      'priority': 'Priority',
      'priority_low': 'Low',
      'priority_mid': 'Medium',
      'priority_high': 'High',
      'clear': 'Clear',
      'tips': 'Tips',
      'no_workflow_tip': 'No workflow yet? Go to "Project" to create one first, then return to this page to select and submit.',
      'add_select_project': 'Select project',
      'add_picker_new_project': '＋ New project',
      'add_new_project_title': 'New project',
      'add_new_project_name_ph': 'Project name (required)',
      'add_new_project_desc_ph': 'Description (optional)',
      'create_project': 'Create Project',
      'no_projects_yet': 'No projects yet',
      'no_projects_desc': 'Tap "Create Project" above or the button below to start.',
      'please_enter_project_name': 'Enter project name',
      'add_new_project_success': 'Project created',
      'add_new_project_create_failed': 'Could not create, try again',
      'add_new_project_id_missing': 'Created, please pick the project in the list',
      'open_project': 'Open Project',
      'boss_dashboard': 'Boss Command Center',
      'boss_dashboard_sub': 'Choose a template and confirm the flow, then give a clear order in one sentence',
      'instruction_flow': 'Instruction Flow',
      'source_dept': 'Source Department',
      'target_dept': 'Target Department',
      'task_goal': 'Task Goal (Boss Directive)',
      'dispatch_preview': 'Dispatch Preview',
      'operator_label': 'Initiator',
      'boss_fallback': 'Boss',
      'flow_preview': 'Flow',
      'priority_preview': 'Priority',
      'input_task_hint': 'Enter your task goal above. It should include expected results, timeline, and acceptance criteria.',
      'message': 'Message',
      'conversation': 'Conversation',
      'collaboration': 'Collaboration & Departments',
      'conversation_tip': 'Manager overview, project groups and workflow conversations',
      'department_tip': 'Browse roles by department, enter personality conversations',
      'loading': 'Loading...',
      'no_conversation': 'No conversations yet',
      'create_group_agent': 'Click the "＋" in the upper right corner to create a project group or digital employee',
      'create_project_group': 'Create Project Group',
      'create_digital_employee': 'Create Digital Employee',
      'add_department': 'Add Department',
      'remove_department': 'Remove Department',
      'dept_name_placeholder': 'Please enter department name',
      'added': 'Added',
      'deleted': 'Deleted',
      'confirm_add': 'Confirm Add',
      'add_role': 'Add Role',
      'remove_role': 'Remove Role',
      'no_role_to_add': 'No roles available to add',
      'no_department': 'No departments yet',
      'no_department_to_add': 'No departments available to add',
      'welcome_back': 'Welcome back',
      'login_subtitle': 'Log in with account or phone number to start using the workbench',
      'account_phone': 'Account / Phone',
      'input_account_phone': 'Please enter account or phone number',
      'password': 'Password',
      'input_password': 'Please enter password',
      'login': 'Login',
      'logging_in': 'Logging in...',
      'no_account': 'Don\'t have an account? Register',
      'please_input_phone': 'Please enter phone number',
      'please_input_password': 'Please enter password',
      'login_success_no_token': 'Login successful but no token returned',
      'login_success': 'Login successful',
      'create_account': 'Create Account',
      'register_subtitle': 'Phone number registration; verification code is used to prevent batch registration by machines (local graphic verification)',
      'phone': 'Phone',
      'input_phone': 'Please enter phone number',
      'verification_code': 'Verification Code',
      'input_captcha': 'Please enter the numbers in the image',
      'captcha_refresh': 'Can\'t see clearly? Click the image to refresh',
      'password_min_length': 'At least 6 characters',
      'confirm_password': 'Confirm Password',
      'input_confirm_password': 'Enter password again',
      'register': 'Register',
      'have_account': 'Already have an account? Go to login',
      'captcha_error': 'Verification code error',
      'passwords_not_match': 'Passwords do not match',
      'register_success': 'Registration successful',
      'register_success_login': 'Registration successful, please login',
      'workbench': 'Workbench',
      'tasks': 'Tasks',
      'communication': 'Communication',
      'graph': 'Graph',
      'feed': 'Feed',
      'by_department': 'By Department',
      'kanban': 'Kanban',
      'list': 'List',
      'issue_command': 'Issue Command',
      'internal': 'Internal',
      'customer': 'Customer',
      'initialize_thread': 'Initialize Thread',
      'broadcast': 'Broadcast',
      'select_thread_or_initialize': 'Please select a thread on the left or initialize first',
      'refresh_graph': 'Refresh Graph',
      'no_node_data': 'No node data',
      'relationship_edges': 'Relationship Edges',
      'refresh_feed': 'Refresh Feed',
      'no_events': 'No events (or interface not open)',
      'source_department': 'Source Department',
      'target_department': 'Target Department',
      'hierarchy_level': 'Hierarchy Level',
      'command_body_required': 'Command body (required)',
      'generate_task_title_optional': 'Generate task title (optional)',
      'parent_task': 'Parent Task',
      'dependent_task': 'Dependent Task',
      'submit': 'Submit',
      'update_progress': 'Update Progress',
      'remark_optional': 'Remark (optional)',
      'save': 'Save',
      'saving': 'Saving…',
      'command_broadcast': 'Command Broadcast',
      'title_optional': 'Title (optional)',
      'broadcast_content': 'Broadcast content',
      'send': 'Send',
      'message_link_task': 'Message Link Task',
      'confirm': 'Confirm',
      'not_started': 'Not Started',
      'in_progress': 'In Progress',
      'blocked': 'Blocked',
      'done': 'Done',
      'unknown': 'Unknown',
      'unnamed_task': 'Unnamed Task',
      'unnamed_workflow': 'Unnamed workflow',
      'workflow_chat_title': 'Workflow chat',
      'workflow_thread_hero': 'Workflow communication thread',
      'workflow_id_prefix': 'Workflow ID: ',
      'workflow_remote_storage_tip': 'Workflow conversation content is stored on the server; clearing on this page only affects locally cached messages already fetched.',
      'thread_default': 'Thread',
      'comms_no_message': '(No messages)',
      'comms_load_failed': '(Failed to load)',
      'modal_need_workflow_first': 'Create a workflow under Project first. Go there now?',
      'modal_pick_workflow_hint': 'Create a workflow under Project and open it once, or tap Select to pick from the list.',
      'go_to_project': 'Go to Project',
      'action_select': 'Select',
      'please_write_task_content': 'Please enter task content first',
      'please_enter_workflow_name': 'Please enter a name',
      'task_pick_none': '(None)',
      'chat_title_fallback': 'Chat',
      'chat_settings_title': 'Chat info',
      'unassigned': 'Unassigned',
      'from_task': 'From Task',
      'to_task': '→ Task',
      'link_task': 'Link Task',
      'please_enter_command_body': 'Please enter command body',
      'please_select_department': 'Please select department',
      'issued': 'Issued',
      'updated': 'Updated',
      'sent': 'Sent',
      'broadcasted': 'Broadcasted',
      'linked': 'Linked',
      'please_select_thread': 'Please select thread',
      'please_enter_content': 'Please enter content',
      'please_enter_broadcast_content': 'Please enter broadcast content',
      'please_select_task': 'Please select task',
      'missing_workflow_id': 'Missing workflow ID',
      'bootstrap_requested': 'Bootstrap requested',
      'basic_info': 'Basic Information',
      'group_name': 'Group Name',
      'group_name_placeholder': 'e.g., XX Client · Delivery Group',
      'client_project_shortname': 'Client / Project Shortname',
      'client_project_placeholder': 'Easy to identify in the list',
      'deliverable_description': 'Deliverable Description',
      'deliverable_placeholder': 'e.g., Mini Program Mall + Admin Backend; Acceptance criteria, key milestones, etc.',
      'plan_reminder': 'Plan & Reminder',
      'expected_delivery_date': 'Expected Launch / Delivery Date',
      'select_date_optional': 'Select date (optional)',
      'daily_report_reminder_time': 'Daily Report Reminder Time',
      'daily_report_reminder_hint': 'After creation, employees will submit daily reports around this time (demo)',
      'other': 'Other',
      'remarks': 'Remarks',
      'remarks_placeholder': 'Project background, client contact person, communication taboos, etc.',
      'create_project_group': 'Create Project Group',
      'please_enter_group_name': 'Please enter group name',
      'created': 'Created',
      'identity_role': 'Identity & Role',
      'name_title': 'Name',
      'name_placeholder': 'e.g., Xiao Ai, A Qiang, Manager Chen',
      'position_responsibility': 'Position / Responsibility',
      'position_placeholder': 'e.g., Project Manager, Frontend, Backend, DevOps, Testing',
      'gender_display': 'Gender (for display)',
      'gender_option_private': 'Prefer not to say',
      'gender_option_male': 'Male',
      'gender_option_female': 'Female',
      'reply_option_brief': 'Concise',
      'reply_option_detailed': 'Detailed',
      'reply_option_bluf': 'Conclusion first, then details',
      'personality_experience': 'Personality & Experience',
      'personality_keywords': 'Personality Keywords',
      'personality_placeholder': 'e.g., Stable, Detail-oriented, Direct communication',
      'hobbies_catchphrases': 'Hobbies / Catchphrases (optional)',
      'hobbies_placeholder': 'To make conversations more natural',
      'project_experience_summary': 'Project Experience Summary',
      'experience_placeholder': 'e.g., Worked on 3 e-commerce mini programs, familiar with payment and orders',
      'collaboration_preference': 'Collaboration Preference',
      'reply_style': 'Reply Style',
      'reply_style_hint': 'When connecting to AI later, replies and daily reports will be generated according to this style first.',
      'additional_notes': 'Additional Notes',
      'additional_notes_placeholder': 'About boss\'s work habits, taboos, communication methods, etc.',
      'agent_creation_note': 'After creation, it will be a local digital employee; can be "laid off" with one click (future version).',
      'create_digital_agent': 'Create Digital Agent',
      'please_enter_name': 'Please enter name',
      'please_enter_position': 'Please enter position',
      'change': 'Change',
      'nickname': 'Nickname',
      'please_enter_nickname': 'Please enter nickname',
      'phone_number': 'Phone Number',
      'save_nickname': 'Save Nickname',
      'nickname_max_20': 'Nickname max 20 characters',
      'saved': 'Saved',
      'change_password': 'Change Password',
      'change_password_hint': 'Please remember your new password after successful change; login status is required for the interface.',
      'current_password': 'Current Password',
      'please_enter_current_password': 'Please enter current password',
      'new_password': 'New Password',
      'new_password_min_6': 'At least 6 characters',
      'confirm_new_password': 'Confirm New Password',
      'reenter_new_password': 'Re-enter new password',
      'save_new_password': 'Save New Password',
      'please_login_first': 'Please login first',
      'current_password_error': 'Current password is incorrect',
      'cannot_use_same_password': 'Cannot use the same password as current',
      'change_failed_retry': 'Change failed, please try again later',
      'change_success': 'Change successful',
      'department_not_found': 'Department not found',
      'missing_department_id': 'Missing department ID',
      'settings_section_account': 'Account & security',
      'settings_section_preferences': 'Preferences',
      'settings_section_privacy': 'Privacy',
      'settings_section_general': 'General',
      'settings_font_size': 'Font size',
      'settings_dark_mode': 'Dark mode',
      'settings_read_receipt': 'Read receipts',
      'settings_read_receipt_sub': 'When off, others cannot see whether you read messages.',
      'settings_online_status': 'Online status',
      'settings_online_status_sub': 'Show whether you are online or offline.',
      'settings_privacy_policy': 'Privacy policy',
      'settings_export_data': 'Export data',
      'settings_check_update': 'Check for updates',
      'settings_version_sub': 'Current version {{ver}}',
      'settings_clear_cache': 'Clear cache',
      'settings_clear_cache_sub': 'Cache: {{size}}',
      'modal_clear_cache_title': 'Clear cache',
      'modal_clear_cache_body': 'Clear cache? Current size: {{size}}',
      'action_clear_cache': 'Clear',
      'toast_clear_cache_ok': 'Cache cleared',
      'toast_clear_cache_fail': 'Could not clear cache',
      'modal_export_data_title': 'Export data',
      'modal_export_data_body': 'Copy digital employees, project groups, workflows, etc. as JSON (back up to notes first).',
      'action_copy_json': 'Copy JSON',
      'export_data_json_label': 'SoloCo data',
      'toast_clipboard_ok': 'Copied to clipboard',
      'toast_clipboard_fail': 'Copy failed',
      'toast_export_fail': 'Export failed',
      'loading_check_update': 'Checking…',
      'modal_check_update_title': 'Updates',
      'modal_check_update_body': 'You are on the latest version ({{ver}}).',
      'action_got_it': 'OK',
      'toast_font_changed': 'Font size: {{size}}',
      'toast_dark_on': 'Dark mode on',
      'toast_dark_off': 'Dark mode off',
      'toast_read_receipt_on': 'Read receipts on',
      'toast_read_receipt_off': 'Read receipts off',
      'toast_online_on': 'Online status visible',
      'toast_online_off': 'Online status hidden',
      'modal_privacy_policy_title': 'Privacy policy',
      'modal_privacy_policy_body': 'We respect your privacy. Your data is used only to improve the product and is not shared with unauthorized third parties.',
      'cache_size_unknown': 'Unknown',
      'language_name_zh': 'Simplified Chinese',
      'language_name_en': 'English',
      'toast_language_zh': 'Switched to Simplified Chinese',
      'toast_language_en': 'Switched to English',
      'font_size_xs': 'Small',
      'font_size_sm': 'Medium',
      'font_size_md': 'Large',
      'font_size_xl': 'Extra large',
      'profile_quick_hire_title': 'Hire employee',
      'profile_quick_hire_sub': 'Add an AI digital employee',
      'profile_quick_group_title': 'Create project group',
      'profile_quick_group_sub': 'New space for collaboration',
      'profile_daily_report': 'Daily report',
      'profile_daily_report_sub': "See your team's work today",
      'profile_assign_task': 'Assign task',
      'profile_assign_task_sub': 'Assign work to your AI team',
      'profile_about_tagline': 'Solo company · AI-powered',
      'profile_about_sub': 'You are the boss; AI is the team',
      'profile_popup_my_team': 'My team',
      'profile_team_count': '{{count}} employees',
      'profile_agents_empty': 'No digital employees yet',
      'profile_agents_empty_sub': 'Tap “Hire employee” to create your first AI teammate',
      'profile_hire_new_cta': '＋ Hire employee',
      'profile_report_team_status': 'Team status',
      'profile_report_no_agents': 'No digital employees',
      'agent_status_busy': 'Busy',
      'agent_status_ready': 'Ready',
      'account_sub_guest': 'Tap to sign in and manage your AI team',
      'account_sub_logged': 'Solo company · Team lead',
      'profile_report_date': '{{m}}/{{d}}/{{y}}',
      'profile_agent_char_fallback': '·',
      'settings_switch_logout_hint': 'Switch account opens the login page for another account; logout clears login on this device and returns to Profile.',
      'language_settings': 'Language settings',
      'switch_account_modal_body': 'You will sign out and go to the login page to use a different account.',
      'go_to_login': 'Go to login',
      'logout_confirm_body': 'Sign out of the current account?',
      'logout_action': 'Sign out',
      'logged_out': 'Signed out',
      'language_switched': 'Language updated',
      'nav_back': 'Back',
      'profile_avatar_guest': 'U',
      'profile_avatar_me': 'Me',
      'my_profile_default': 'My profile',
      'profile_info_nav': 'Profile',
      'please_complete_phone': 'Please add a valid phone number',
      'uploading': 'Uploading',
      'avatar_updated': 'Avatar updated',
      'model_settings_tip': 'Keys stay on this device. Saving runs a live check (GET /models, or a minimal chat if unavailable). Chat calls use the base URL (OpenAI-compatible). For WeChat mini programs, add the domain as an allowed request domain, or use a same-origin proxy.',
      'model_settings_tip_title': 'Security',
      'model_section_connection': 'Connection',
      'model_section_model': 'Model',
      'model_label_api_key': 'API Key',
      'model_label_base_url': 'API base URL (incl. /v1)',
      'model_label_model_name': 'Model name',
      'model_placeholder_key': 'sk-… or provider key',
      'model_validate_key_required': 'Please enter your API key',
      'model_validate_url_required': 'Please enter the API base URL',
      'model_validate_url_invalid': 'Invalid URL — use a valid http(s) address',
      'model_validate_url_protocol': 'Only http and https are allowed',
      'model_validate_url_need_v1': 'Path must end with /v1 (e.g. https://api.openai.com/v1)',
      'model_validate_model_required': 'Please enter a model name',
      'model_validate_model_too_long': 'Model name is too long (max 128 characters)',
      'model_verify_loading': 'Verifying connection…',
      'model_verify_auth_failed': 'Invalid API key or access denied',
      'model_verify_chat_failed': 'Chat endpoint rejected the request',
      'model_verify_http': 'Server returned an error',
      'model_verify_network': 'Network error or service unreachable',
      'model_verify_failed': 'Connection check failed',
      'staff_api_nav': 'Staff & models',
      'staff_api_tip_title': 'About',
      'staff_api_tip': 'Add model IDs you use (e.g. gpt-4o-mini). They appear as quick picks on Staff & models.',
      'staff_api_section_add': 'Add model name',
      'staff_api_section_list': 'Saved models',
      'staff_api_add_placeholder': 'Model ID or name',
      'staff_api_add_btn': 'Add',
      'staff_api_empty': 'No models yet. Add one above.',
      'staff_api_empty_name': 'Enter a model name',
      'staff_api_remove': 'Remove',
      'staff_api_remove_title': 'Remove model',
      'staff_api_remove_body': 'Remove "{{name}}" from the list? Assigned staff settings stay unchanged.',
      'staff_api_added': 'Added',
      'staff_api_removed': 'Removed',
      'agent_model_pick_from_list': 'Pick from list',
      'agent_model_assign_nav': 'Staff & models',
      'agent_model_assign_tip_title': 'About',
      'agent_model_assign_tip':
        'Tap Add model first to configure, verify, and add models to the list. Tap an employee’s name to pick a model; your choice is saved automatically.',
      'agent_model_add_model_btn': 'Add model',
      'agent_model_added_to_list': 'Added',
      'agent_model_api_already_added': 'This API has already been added',
      'agent_model_name_exists': 'This model name already exists',
      'agent_model_view_models_btn': 'View models',
      'agent_model_detail_title': 'Model details',
      'agent_model_view_empty': 'No saved models yet',
      'agent_model_field_empty': 'Not set',
      'agent_model_delete_saved': 'Delete model',
      'agent_model_delete_saved_title': 'Delete model',
      'agent_model_delete_saved_body': 'Remove "{{name}}"? You can add it again later.',
      'agent_model_deleted': 'Removed',
      'agent_model_confirm_delete': 'Delete',
      'agent_model_delete_failed': 'Could not delete. Please try again.',
      'agent_model_staff_list_title': 'Staff list',
      'agent_model_section_staff': 'Assign to digital employees',
      'agent_model_batch_placeholder': 'Batch: model name',
      'agent_model_apply_batch': 'Apply to selected',
      'agent_model_select_all': 'Select all',
      'agent_model_save_all': 'Save all',
      'agent_model_save_one': 'Save row',
      'agent_model_saved': 'Saved',
      'agent_model_empty': 'No digital employees yet. Create one from the Messages tab (＋) first.',
      'agent_model_row_placeholder': 'Pick a model',
      'agent_model_none_selected': 'Select employees first',
      'agent_model_batch_applied': 'Applied model to {{count}} staff',
      'agent_llm_system_prompt': 'You are digital employee "{{name}}" ({{role}}). Reply concisely and professionally, in character.',
      'chat_search_nav': 'Search chats',
      'chat_search_placeholder': 'Search messages',
      'chat_search_no_hits': 'No results',
      'chat_search_hint': 'Enter a keyword to search',
      'load_failed_short': 'Load failed',
      'time_yesterday': 'Yesterday',
      'date_month_day': '{{month}}/{{day}}',
      'role_count_suffix': ' roles',
      'manager_overview_title': 'Manager overview',
      'digital_employee_fallback': 'Digital employee',
      'project_group_fallback': 'Project group',
      'abbr_manager': 'M',
      'abbr_group': 'G',
      'abbr_project': 'P',
      'abbr_staff': '·',
      'sender_system': 'Sys',
      'manager_feed_keyword': 'Manager overview',
      'home_sender_me': 'Me',
      'chat_no_messages': 'No messages yet',
      'feed_badge_must_read': 'Must-read',
      'vt_demo_group_mall_name': 'Demo · Mall mini program',
      'vt_demo_group_mall_desc': 'Client A delivery',
      'vt_demo_agent_chen_name': 'Chen',
      'vt_demo_agent_xiao_name': 'Aria',
      'vt_demo_agent_qiang_name': 'Qiang',
      'role_title_pm': 'Project Manager',
      'role_title_frontend': 'Frontend',
      'role_title_backend': 'Backend',
      'vt_unnamed_group': 'Untitled group',
      'vt_default_agent_name': 'Digital employee',
      'vt_member_default': 'Member',
      'vt_preview_me_prefix': 'Me: ',
      'vt_group_created_toast': 'Group created — start collaborating',
      'vt_demo_group_last_preview': 'PM: integration window aligned for this week.',
      'vt_demo_agent1_last_preview': 'Stand-up moved to 10:00 tomorrow.',
      'vt_demo_agent2_last_preview': 'Home skeleton screen submitted.',
      'vt_demo_agent3_last_preview': 'Order API Swagger updated.',
      'hall_welcome_body':
        'Welcome to the company all-hands group. Digital employees submit daily reports at 21:00; the manager digest arrives at 21:30. You can @ anyone to assign work.',
      'hall_digest_start': '— Daily reports at 21:00 —',
      'hall_daily_prefix': 'Daily: ',
      'agent_chat_seed_body': "Hi, I'm {{name}} ({{role}}). Here's my daily summary.\n{{summary}}",
      'agent_seed_role_fallback': 'Role',
      'agent_seed_ready_line': '[{{role}}] Ready and awaiting instructions.',
      'seed_inbox_title': 'Hello',
      'seed_inbox_question': 'Any questions?',
      'vt_agent_ready_hint': 'Ready when you are',
      'briefing_schedule_note': 'Daily reports at 21:00; manager digest at 21:30',
      'briefing_time_2100': 'Today 21:00',
      'briefing_time_2130': 'Today 21:30',
      'briefing_employee_summary': '[{{role}}] Routine progress today; risks: none blocking; tomorrow: continue the current iteration.',
      'briefing_manager_summary': '[Manager] Overall progress is on track. Focus: client acceptance aligned; tomorrow prioritize payment integration. {{schedule}}',
      'vt_hall_sender_1': 'Chen (Project Manager)',
      'vt_hall_sender_2': 'Aria (Frontend)',
      'vt_hall_sender_3': 'Qiang (Backend)',
      'chat_input_placeholder': 'Type a message…',
      'chat_requesting': 'Sending…',
      'multi_cancel': 'Cancel',
      'multi_selected': '{{count}} selected',
      'action_copy': 'Copy',
      'action_forward': 'Forward',
      'action_delete': 'Delete',
      'toast_copied': 'Copied',
      'toast_copied_paste': 'Copied — paste in another chat',
      'toast_select_msg_first': 'Select messages first',
      'toast_copied_merge': 'Merged content copied',
      'toast_remote_no_delete': 'Cannot delete in remote sessions',
      'delete_messages_title': 'Delete messages',
      'delete_messages_body': 'Delete {{count}} selected messages (local only)?',
      'toast_remote_no_recall': 'Cannot recall remote messages',
      'toast_recalled': 'Recalled',
      'toast_remote_cannot_delete': 'Cannot delete remote messages',
      'delete_one_title': 'Delete message',
      'delete_one_body': 'Remove this message from this device?',
      'menu_copy': 'Copy',
      'menu_recall': 'Recall',
      'menu_delete': 'Delete',
      'menu_forward': 'Forward',
      'menu_multiselect': 'Multi-select',
      'message_empty_mark': '(empty)',
      'toast_set_api_key_in_profile': 'Set API key in Profile → Staff & models first',
      'toast_agent_content_missing': 'No agent content — check /api/agents',
      'assistant_name_short': 'Assistant',
      'model_err_title': 'Model request failed — check key and domain',
      'model_err_body': 'Model call failed: check key, URL, and mini program request domain.',
      'sender_system_name': 'System',
      'chat_list_title': 'Messages',
      'boss_chat_name': 'Boss',
      'engineering_department': 'Engineering',
      'reply_ok_title': 'Reply',
      'reply_ok_content': 'OK, got it',
      'workbench_id_label': 'ID: ',
      'wb_from_dept': 'From: ',
      'wb_to_dept': 'To: ',
      'wb_link_from_task': 'Link from task: ',
      'wb_link_to_task': 'Link to task: ',
      'wb_msg_placeholder': 'Message content',
      'wb_optional_paren': '(optional)',
      'wb_parent_prefix': 'Parent',
      'wb_dep_prefix': 'Depends',
      'wb_task_prefix': 'Task {{id}}',
      'wb_node_fallback': 'Node',
      'tab_switch_failed': 'Switch failed',
      'dept_roles_empty': 'No roles in this department',
      'dept_roles_empty_hint': 'Check that local persona data includes this category; pull to retry.',
      'dept_roles_hero_title': 'Roles',
      'dept_roles_hero_meta': '{{count}} · tap to chat',
      'dept_roles_nav': 'Roles',
      'cs_no_desc': 'No description',
      'cs_client_prefix': 'Client: ',
      'cs_delivery_prefix': 'Delivery: ',
      'cs_digital_employee_role': 'Digital employee',
      'cs_one_on_one': '1:1 work chat',
      'cs_hq_desc': 'All-hands · daily reports & manager overview',
      'cs_manager_desc': 'Daily 21:30 overview · traceable system chat',
      'cs_persona_desc': 'Persona chat · local demo (no LLM)',
      'cs_local_session': 'Local session',
      'cs_find_chat_history': 'Search chat history',
      'cs_group_manage': 'Group management',
      'cs_group_notice': 'Group notice',
      'cs_pin_chat': 'Pin chat',
      'cs_mute': 'Mute notifications',
      'cs_clear_history': 'Clear chat history',
      'cs_hq_members_modal': 'All-hands · {{count}} digital employees',
      'cs_no_members': 'No members',
      'cs_collab_members_plain': 'Members',
      'cs_collab_members_named': '「{{name}}」 members',
      'cs_notice_hq_body': 'Daily reports at 21:00; manager overview at 21:30.',
      'cs_notice_empty': 'No notice yet. Add a description when creating a project group.',
      'cs_clear_modal_title': 'Clear chat history',
      'cs_clear_modal_body': 'Delete local messages for this chat?',
      'cs_cleared_remote_cache': 'Local cache cleared',
      'cs_cleared': 'Cleared',
      'cs_no_message_stub': 'No messages',
      'dept_def_goal': 'Goal',
      'dept_def_goal_ph': 'What you want to achieve this phase',
      'dept_def_priority': 'Priority',
      'dept_def_roles': 'Roles (multi)',
      'dept_def_submit': 'Generate task draft',
      'dept_def_err_goal': 'Enter a goal',
      'dept_def_err_role': 'Select a role',
      'dept_def_ok': 'Draft generated (pending backend)',
      'dept_eng_err_goal': 'Enter sprint goal',
      'dept_eng_err_peer': 'Add at least one teammate',
      'dept_eng_ok': 'Sprint draft generated (pending backend)',
      'dept_eng_eyebrow': 'R&D delivery',
      'dept_eng_sprint_h': 'Sprint goal',
      'dept_eng_sprint_ph': 'Scope, acceptance criteria, and deadline',
      'dept_eng_debt_h': 'Tech debt notes',
      'dept_eng_debt_ph': 'Briefly describe one debt item…',
      'dept_eng_debt_add': 'Add',
      'dept_eng_debt_del': 'Del',
      'dept_eng_debt_empty': 'No items yet—review in sprint planning.',
      'dept_eng_release_h': 'Release window',
      'dept_eng_release_slot_0': 'Thu evening slot',
      'dept_eng_release_slot_1': 'Fri noon slot',
      'dept_eng_release_slot_2': 'Mon canary',
      'dept_eng_release_slot_3': 'TBD / version train',
      'dept_eng_squad_h': 'Delivery squad',
      'dept_eng_squad_sub': 'Tap members (multi-select)',
      'dept_eng_reset': 'Clear',
      'dept_eng_submit': 'Generate sprint draft',
      'dept_sup_err_body': 'Enter request summary',
      'dept_sup_err_skill': 'Select a skill',
      'dept_sup_ok': 'Support ticket created (pending backend)',
      'dept_spe_err_brief': 'Enter task brief',
      'dept_spe_err_step': 'Enter at least one step',
      'dept_spe_err_expert': 'Select expert roles',
      'dept_spe_ok': 'Orchestration draft generated (pending backend)',
      'dept_spe_eyebrow': 'Cross-domain orchestration',
      'dept_spe_brief_h': 'Task brief',
      'dept_spe_brief_ph': 'Systems, agents, compliance boundaries, desired output shape',
      'dept_spe_mcp_h': 'Enable MCP tool extensions',
      'dept_spe_steps_h': 'Orchestration steps (ordered)',
      'dept_spe_step_ph': 'Step description',
      'dept_spe_step_add': '＋ Step',
      'dept_spe_pool_h': 'Expert pool (multi-select)',
      'dept_spe_reset': 'Reset',
      'dept_spe_submit': 'Generate orchestration plan',
      'dept_sal_err_name': 'Enter opportunity name',
      'dept_sal_err_role': 'Select a sales role',
      'dept_sal_ok': 'Deal draft saved (pending backend)',
      'dept_mkt_err_theme': 'Enter campaign theme',
      'dept_mkt_err_role': 'Select at least one role',
      'dept_mkt_ok': 'Brief generated (pending backend)',
      'dept_mkt_eyebrow': 'Growth & comms',
      'dept_mkt_campaign_h': 'Campaign codename / theme',
      'dept_mkt_campaign_ph': 'e.g. Launch wave 2 awareness',
      'dept_mkt_matrix_h': 'Channel matrix (reach)',
      'dept_mkt_mx_douyin': 'Short video',
      'dept_mkt_mx_wx': 'WeChat ecosystem',
      'dept_mkt_mx_seo': 'Search / SEO',
      'dept_mkt_mx_kol': 'Creators / KOL',
      'dept_mkt_mv_on': 'Primary',
      'dept_mkt_mv_off': 'TBD',
      'dept_mkt_brief_h': 'Core message & asset asks',
      'dept_mkt_brief_ph': 'One-liner, three proofs, asset specs',
      'dept_mkt_team_h': 'Squad (multi-select)',
      'dept_mkt_reset': 'Reset',
      'dept_mkt_submit': 'Generate campaign brief',
      'dept_prd_eyebrow': 'Product & roadmap',
      'dept_prd_box_h': 'Timebox',
      'dept_prd_box_0': 'This week',
      'dept_prd_box_1': 'This month',
      'dept_prd_box_2': 'This quarter',
      'dept_prd_box_3': 'Next quarter',
      'dept_prd_hypo_h': 'Hypothesis under test',
      'dept_prd_hypo_ph': 'Measurable user or business signal, e.g. seat-based pricing conversion',
      'dept_prd_focus_h': 'Focus mode',
      'dept_prd_mode_discovery': 'Discovery',
      'dept_prd_mode_delivery': 'Delivery',
      'dept_prd_team_h': 'PM squad (multi-select)',
      'dept_prd_reset': 'Clear',
      'dept_prd_submit': 'Generate roadmap slice',
      'dept_pm_eyebrow': 'Delivery governance',
      'dept_pm_ms_h': 'Milestones / checkpoints',
      'dept_pm_ms_ph': 'Describe the gate and done criteria',
      'dept_pm_ms_del': 'Del',
      'dept_pm_ms_add': '＋ Add checkpoint',
      'dept_pm_risk_h': 'Overall risk heat (1–5 self-rated)',
      'dept_pm_gov_h': 'Governance roles',
      'dept_pm_reset': 'Clear',
      'dept_pm_submit': 'Export governance memo',
      'dept_prd_err_hypo': 'Enter hypothesis',
      'dept_prd_err_pm': 'Select PM role',
      'dept_prd_ok': 'Roadmap slice generated (pending backend)',
      'dept_pm_err_milestone': 'Enter at least one milestone',
      'dept_pm_err_gov': 'Select governance role',
      'dept_pm_ok': 'Governance memo draft generated (pending backend)',
      'dept_paid_err_kpi': 'Enter KPI direction',
      'dept_paid_err_role': 'Select collaborator roles',
      'dept_paid_ok': 'Media plan generated (pending backend)',
      'dept_paid_eyebrow': 'Spend & performance',
      'dept_paid_pace_h': 'Budget pacing (self-assessed)',
      'dept_paid_pace_hint': 'Align on whether to scale up or pull back—even without a live account.',
      'dept_paid_channels_h': 'Channels',
      'dept_paid_ch_search': 'Search',
      'dept_paid_ch_social': 'Social feeds',
      'dept_paid_ch_shop': 'Commerce',
      'dept_paid_kpi_h': 'Goal / KPI',
      'dept_paid_kpi_ph': 'e.g. CPA −12%, remarketing list to 50k devices',
      'dept_paid_roles_h': 'Collaborators',
      'dept_paid_reset': 'Reset',
      'dept_paid_submit': 'Generate media action sheet',
      'dept_sal_eyebrow': 'Pipeline',
      'dept_sal_stage_h': 'Stage',
      'dept_sal_stage_disc': 'Discover',
      'dept_sal_stage_qual': 'Qualify',
      'dept_sal_stage_prop': 'Propose',
      'dept_sal_stage_close': 'Close',
      'dept_sal_deal_h': 'Opportunity name',
      'dept_sal_deal_ph': 'e.g. Enterprise annual framework',
      'dept_sal_next_h': 'Next step / blocker',
      'dept_sal_next_ph': 'Next meeting, materials, or competitor moves',
      'dept_sal_skill_h': 'Sales capability',
      'dept_sal_reset': 'Clear',
      'dept_sal_submit': 'Save deal draft',
      'dept_sup_eyebrow': 'Customer & internal support',
      'dept_sup_type_h': 'Ticket type',
      'dept_sup_type_0': 'How-to',
      'dept_sup_type_1': 'Outage / broken',
      'dept_sup_type_2': 'Billing & compliance',
      'dept_sup_type_3': 'Data & reporting',
      'dept_sup_sla_h': 'Response SLA',
      'dept_sup_sla_std_l': 'Standard',
      'dept_sup_sla_std_d': 'Business-day queue',
      'dept_sup_sla_urg_l': 'Urgent',
      'dept_sup_sla_urg_d': 'Escalation & on-call',
      'dept_sup_body_h': 'Summary',
      'dept_sup_body_ph': 'Symptoms, blast radius, tried steps, target recovery time',
      'dept_sup_assign_h': 'Assign capability',
      'dept_sup_reset': 'Reset',
      'dept_sup_submit': 'Create support ticket',
      'dept_fin_err_ask': 'Enter request details',
      'dept_fin_err_role': 'Select finance role',
      'dept_fin_ok': 'Finance task started (pending backend)',
      'dept_fin_eyebrow': 'Finance discipline',
      'dept_fin_period_h': 'Accounting period',
      'dept_fin_period_ph': 'Pick year-month',
      'dept_fin_job_h': 'Job type',
      'dept_fin_job_close_l': 'Close',
      'dept_fin_job_close_h': 'Close & reporting',
      'dept_fin_job_fpa_l': 'Forecast',
      'dept_fin_job_fpa_h': 'Rolling forecast / analytics',
      'dept_fin_job_tax_l': 'Tax',
      'dept_fin_job_tax_h': 'Planning & compliance',
      'dept_fin_ask_h': 'Request details',
      'dept_fin_ask_ph': 'Reports needed, variance drivers, tax assumptions, or control focus',
      'dept_fin_role_h': 'Finance roles',
      'dept_fin_reset': 'Reset',
      'dept_fin_submit': 'Start finance task',
      'dept_des_err_deliver': 'Select at least one deliverable',
      'dept_des_err_seat': 'Select a primary design seat',
      'dept_des_ok': 'Design ticket generated (pending backend)',
      'dept_des_eyebrow': 'Experience & visual',
      'dept_des_track_h': 'Workstream',
      'dept_des_track_ui': 'UI',
      'dept_des_track_ux': 'Research',
      'dept_des_track_system': 'Systems',
      'dept_des_deliver_h': 'Deliverables',
      'dept_des_del_hifi': 'Hi-fi key screens',
      'dept_des_del_empty': 'Empty / error states',
      'dept_des_del_ds': 'Design system delta',
      'dept_des_a11y_h': 'Accessibility audit',
      'dept_des_notes_h': 'Notes / constraints',
      'dept_des_notes_ph': 'Brand guardrails, pixel rules, motion budget…',
      'dept_des_seat_h': 'Seat (pick a role)',
      'dept_des_reset': 'Reset',
      'dept_des_submit': 'Generate design ticket',
      'dept_qa_err_scope': 'Enter verification scope',
      'dept_qa_err_severity': 'Select severity',
      'dept_qa_err_role': 'Select QA role',
      'dept_qa_ok': 'Verification ticket created (pending backend)',
      'dept_qa_eyebrow': 'Quality gate',
      'dept_qa_scope_h': 'Verification scope',
      'dept_qa_scope_ph': 'Flows, APIs, browser matrix, regression set name…',
      'dept_qa_sev_h': 'Severity focus (multi-select)',
      'dept_qa_env_h': 'Environment',
      'dept_qa_env_0': 'Development',
      'dept_qa_env_1': 'Staging',
      'dept_qa_env_2': 'Prod read-only mirror',
      'dept_qa_env_3': 'Production (controlled window)',
      'dept_qa_team_h': 'QA squad',
      'dept_qa_reset': 'Reset',
      'dept_qa_submit': 'Create verification ticket',
      'dept_spa_err_goal': 'Enter experience goals',
      'dept_spa_err_team': 'Select tech team',
      'dept_spa_ok': 'Spatial delivery draft generated (pending backend)',
      'dept_spa_eyebrow': 'Spatial experience',
      'dept_spa_fps_h': 'Target frame budget (FPS)',
      'dept_spa_tier_h': 'Scene complexity',
      'dept_spa_tier_low': 'Light',
      'dept_spa_tier_mid': 'Medium',
      'dept_spa_tier_high': 'Heavy',
      'dept_spa_goal_h': 'Experience & performance goals',
      'dept_spa_goal_ph': 'Comfort, gesture latency, tracking tolerance, multiplayer sync…',
      'dept_spa_team_h': 'Spatial tech squad',
      'dept_spa_reset': 'Clear',
      'dept_spa_submit': 'Generate spatial delivery sheet',
      'dept_aca_err_task': 'Enter research task',
      'dept_aca_err_lead': 'Select lead scholar',
      'dept_aca_ok': 'Academic brief generated (pending backend)',
      'dept_aca_eyebrow': 'Narrative & worldbuilding',
      'dept_aca_disc_h': 'Disciplinary lens',
      'dept_aca_disc_anthro': 'Anthropology',
      'dept_aca_disc_hist': 'History',
      'dept_aca_disc_psych': 'Psychology',
      'dept_aca_disc_hint': 'The lens shapes the questions; the roster matches your data for the current thread.',
      'dept_aca_task_h': 'Research / canon task',
      'dept_aca_task_ph': 'Contradictions to resolve, facts to verify, or motive threads',
      'dept_aca_lead_h': 'Lead scholar (single)',
      'dept_aca_reset': 'Reset',
      'dept_aca_submit': 'Generate academic brief',
      'agent_drawer_close': 'Close',
      'agent_drawer_expertise': 'Expertise: ',
      'agent_drawer_when': 'When to use: ',
      'agent_drawer_create_task': 'Create task',
      'err_network': 'Network error — try again',
      'err_timeout_net': 'Timeout — try another network',
      'err_domain': 'Request blocked — check domain or network',
      'err_abort': 'Request aborted',
      'err_ssl': 'Secure connection failed',
      'err_login_expired': 'Session expired — sign in again',
      'err_upload_failed': 'Upload failed',
      'err_request_failed': 'Request failed',
      'err_service_unavailable': 'Service unavailable — try later',
      'err_404_frontend': '404: request did not reach API (frontend/Nginx)',
      'err_404_double_api': '404: extra /api in URL — check .env',
      'err_404_api': '404: check Swagger path and backend version',
      'msg_dept_engineering_title': 'Engineering',
      'msg_dept_engineering_desc': 'Build the future—one commitment at a time.',
      'msg_dept_design_title': 'Design',
      'msg_dept_design_desc': 'Make it beautiful, usable, and delightful.',
      'msg_dept_paid_media_title': 'Paid Media',
      'msg_dept_paid_media_desc': 'Turn ad spend into measurable business outcomes.',
      'msg_dept_sales_title': 'Sales',
      'msg_dept_sales_desc': 'Turn pipeline into revenue—not CRM busywork.',
      'msg_dept_marketing_title': 'Marketing',
      'msg_dept_marketing_desc': 'Authentic engagement that grows your audience.',
      'msg_dept_product_title': 'Product',
      'msg_dept_product_desc': 'Build the right thing at the right time.',
      'msg_dept_project_management_title': 'Project Management',
      'msg_dept_project_management_desc': 'Keep delivery on track and on budget.',
      'msg_dept_testing_title': 'Quality Assurance',
      'msg_dept_testing_desc': 'Break things in QA so users do not.',
      'msg_dept_support_title': 'Support',
      'msg_dept_support_desc': 'The backbone that turns intent into action.',
      'msg_dept_spatial_computing_title': 'Spatial Computing',
      'msg_dept_spatial_computing_desc': 'Craft immersive experiences for what comes next.',
      'msg_dept_specialized_title': 'Specialized',
      'msg_dept_specialized_desc': 'Cross-domain experts for high-complexity work.',
      'msg_dept_finance_title': 'Finance',
      'msg_dept_finance_desc': 'Accounting, FP&A, tax, and investment insight.',
      'msg_dept_game_development_title': 'Game Development',
      'msg_dept_game_development_desc': 'Engine, gameplay, and toolchain—from prototype to ship.',
      'msg_dept_academic_title': 'Academic',
      'msg_dept_academic_desc': 'Rigorous scholarship for worldbuilding and narrative design.',
      
      // Engineering Department Personnel
      'eng_frontend_name': 'Frontend Developer',
      'eng_frontend_intro': 'React/Vue/Angular, UI implementation and performance',
      'eng_frontend_detail': 'Responsible for modern web applications, pixel-perfect interfaces, and core experience optimization.',
      'eng_frontend_expertise': 'React/Vue/Angular, UI and performance',
      'eng_frontend_whenToUse': 'Modern web applications, core page experience optimization',
      
      'eng_backend_name': 'Backend Architect',
      'eng_backend_intro': 'API design, database architecture, scalability',
      'eng_backend_detail': 'Build stable and scalable server-side systems and data layers.',
      'eng_backend_expertise': 'API, database, scalable architecture',
      'eng_backend_whenToUse': 'Server-side systems, microservices, cloud infrastructure',
      
      'eng_mobile_name': 'Mobile App Builder',
      'eng_mobile_intro': 'iOS/Android, React Native, Flutter',
      'eng_mobile_detail': 'Responsible for native and cross-platform mobile app development.',
      'eng_mobile_expertise': 'Native and cross-platform mobile development',
      'eng_mobile_whenToUse': 'Mobile app from 0 to 1',
      
      'eng_ai_name': 'AI Engineer',
      'eng_ai_intro': 'Machine learning models, deployment, AI integration',
      'eng_ai_detail': 'Integrate model capabilities into products and implement AI-driven processes.',
      'eng_ai_expertise': 'Model training, inference deployment, AI integration',
      'eng_ai_whenToUse': 'Machine learning features, data pipelines, AI applications',
      
      // Design Department Personnel
      'des_ui_name': 'UI Designer',
      'des_ui_intro': 'Visual design, component library, design system',
      'des_ui_detail': 'Establish interface standards and component systems to ensure brand consistency.',
      'des_ui_expertise': 'Visual design and design systems',
      'des_ui_whenToUse': 'Interface creation, brand consistency, component design',
      
      'des_ux_name': 'UX Researcher',
      'des_ux_intro': 'User testing, behavior analysis, research',
      'des_ux_detail': 'Discover problems and output actionable insights through user research.',
      'des_ux_expertise': 'Usability testing and user research',
      'des_ux_whenToUse': 'Understanding users, validating solutions, experience improvement',
      
      'des_arch_name': 'UX Architect',
      'des_arch_intro': 'Technical architecture, CSS systems and implementation',
      'des_arch_detail': 'Build the engineering bridge between design and frontend implementation.',
      'des_arch_expertise': 'CSS architecture and implementation standards',
      'des_arch_whenToUse': 'Large frontend project standardization',
      
      // Paid Media Department Personnel
      'paid_ppc_name': 'PPC Campaign Strategist',
      'paid_ppc_intro': 'Google/Microsoft/Amazon advertising strategy',
      'paid_ppc_detail': 'Plan account structure, budget allocation, and bidding strategies.',
      'paid_ppc_expertise': 'Account architecture and bidding optimization',
      'paid_ppc_whenToUse': 'Account setup, scaling, performance diagnosis',
      
      'paid_tracking_name': 'Tracking & Measurement Expert',
      'paid_tracking_intro': 'GTM, GA4, conversion tracking, CAPI',
      'paid_tracking_detail': 'Ensure attribution and data consistency for ad campaigns.',
      'paid_tracking_expertise': 'Tracking and attribution data pipeline',
      'paid_tracking_whenToUse': 'Tracking audit, platform migration, new projects',
      
      'paid_creative_name': 'Ad Creative Strategist',
      'paid_creative_intro': 'Copy strategy, creative testing, creative iteration',
      'paid_creative_detail': 'Improve ad click-through and conversion rates through continuous testing.',
      'paid_creative_expertise': 'Creative strategy and A/B testing',
      'paid_creative_whenToUse': 'Creative fatigue, material updates, campaign promotion',
      
      // Sales Department Personnel
      'sales_outbound_name': 'Outbound Strategist',
      'sales_outbound_intro': 'Signal-based multi-channel prospecting and ICP targeting',
      'sales_outbound_detail': 'Build outreach strategies and cadences in a research-driven manner.',
      'sales_outbound_expertise': 'Outreach strategy and lead qualification',
      'sales_outbound_whenToUse': 'Cold start customer acquisition, new market expansion',
      
      'sales_deal_name': 'Deal Strategist',
      'sales_deal_intro': 'MEDDPICC qualification, competitive positioning, win planning',
      'sales_deal_detail': 'Identify deal risks and develop actionable win paths.',
      'sales_deal_expertise': 'Complex deal strategy',
      'sales_deal_whenToUse': 'Key opportunity advancement, quarterly冲刺',
      
      'sales_se_name': 'Sales Engineer',
      'sales_se_intro': 'Technical demonstrations, POC scoping, battle cards',
      'sales_se_detail': 'Bridge product capabilities and business value to win technical evaluations.',
      'sales_se_expertise': 'Pre-sales technical and demonstration',
      'sales_se_whenToUse': 'POC, technical Q&A, competitive positioning',
      
      // Marketing Department Personnel
      'mkt_growth_name': 'Growth Hacker',
      'mkt_growth_intro': 'User acquisition, viral loops, conversion experiments',
      'mkt_growth_detail': 'Find replicable growth actions through rapid experimentation.',
      'mkt_growth_expertise': 'Growth experiments and funnel optimization',
      'mkt_growth_whenToUse': 'User growth, conversion optimization',
      
      'mkt_content_name': 'Content Creator',
      'mkt_content_intro': 'Multi-platform content and editorial cadence',
      'mkt_content_detail': 'Build content assets and consistently output brand narratives.',
      'mkt_content_expertise': 'Content strategy and brand expression',
      'mkt_content_whenToUse': 'Content operation, brand building',
      
      'mkt_seo_name': 'SEO Expert',
      'mkt_seo_intro': 'Technical SEO, content strategy, link building',
      'mkt_seo_detail': 'Drive organic traffic and high-intent user growth.',
      'mkt_seo_expertise': 'Organic search growth',
      'mkt_seo_whenToUse': 'Long-term customer acquisition, reduce acquisition costs',
      
      // Product Department Personnel
      'prd_pm_name': 'Product Manager',
      'prd_pm_intro': 'Discovery, roadmap, GTM, results measurement',
      'prd_pm_detail': 'Connect user needs, business goals, and R&D execution.',
      'prd_pm_expertise': 'Product full lifecycle',
      'prd_pm_whenToUse': 'Roadmap planning, requirement prioritization',
      
      'prd_pri_name': 'Sprint Prioritization',
      'prd_pri_intro': 'Agile planning, resource allocation, backlog management',
      'prd_pri_detail': 'Help teams prioritize high-value features with limited resources.',
      'prd_pri_expertise': 'Prioritization and sprint management',
      'prd_pri_whenToUse': 'Sprint planning, task sorting',
      
      'prd_feedback_name': 'Feedback Synthesizer',
      'prd_feedback_intro': 'User feedback analysis, insight extraction',
      'prd_feedback_detail': 'Transform scattered feedback into actionable improvement lists.',
      'prd_feedback_expertise': 'Feedback structuring and insights',
      'prd_feedback_whenToUse': 'Version review, user insights',
      
      // Project Management Department Personnel
      'pm_shepherd_name': 'Shepherd Plan',
      'pm_shepherd_intro': 'Cross-functional coordination, timeline and risk management',
      'pm_shepherd_detail': 'End-to-end推动多团队项目稳定交付。',
      'pm_shepherd_expertise': 'Project coordination and risk management',
      'pm_shepherd_whenToUse': 'Complex project execution phase',
      
      'pm_experiment_name': 'Experiment Tracker',
      'pm_experiment_intro': 'A/B testing and hypothesis validation management',
      'pm_experiment_detail': 'Standardize experimental processes and improve the credibility of experimental conclusions.',
      'pm_experiment_expertise': 'Experiment management and analysis',
      'pm_experiment_whenToUse': 'Feature validation, data-driven decisions',
      
      'pm_jira_name': 'Jira Workflow Administrator',
      'pm_jira_intro': 'Jira + Git traceable delivery',
      'pm_jira_detail': 'Establish consistent processes for tasks, branches, and releases.',
      'pm_jira_expertise': 'Delivery process governance',
      'pm_jira_whenToUse': 'Team collaboration standardization',
      
      // QA Department Personnel
      'qa_evidence_name': 'Evidence Collector',
      'qa_evidence_intro': 'Screenshot-oriented quality assurance and issue recording',
      'qa_evidence_detail': 'Improve defect communication efficiency through visual evidence.',
      'qa_evidence_expertise': 'Visual QA',
      'qa_evidence_whenToUse': 'UI testing, visual acceptance',
      
      'qa_api_name': 'API Tester',
      'qa_api_intro': 'Interface verification and integration testing',
      'qa_api_detail': 'Ensure the stability and correctness of critical interfaces.',
      'qa_api_expertise': 'API testing and integration support',
      'qa_api_whenToUse': 'Interface regression, integration testing',
      
      'qa_perf_name': 'Performance Benchmark Tester',
      'qa_perf_intro': 'Performance testing, capacity evaluation, optimization recommendations',
      'qa_perf_detail': 'Identify system bottlenecks and provide actionable optimization paths.',
      'qa_perf_expertise': 'Performance evaluation and tuning',
      'qa_perf_whenToUse': 'Pre-launch stress testing, performance anomalies',
      
      // Support Department Personnel
      'sup_response_name': 'Support Responder',
      'sup_response_intro': 'Customer service, problem solving, escalation management',
      'sup_response_detail': 'Establish high-quality support experiences and promote issue closure.',
      'sup_response_expertise': 'Customer support system',
      'sup_response_whenToUse': 'Support process building, complaint handling',
      
      'sup_analytics_name': 'Analytics Reporter',
      'sup_analytics_intro': 'Dashboards, KPI, business insights',
      'sup_analytics_detail': 'Transform business data into executable strategies.',
      'sup_analytics_expertise': 'BI analysis and visualization',
      'sup_analytics_whenToUse': 'Business review, metric tracking',
      
      'sup_compliance_name': 'Legal Compliance Checker',
      'sup_compliance_intro': 'Compliance review, regulatory requirements, risk management',
      'sup_compliance_detail': 'Ensure business processes comply with policies and industry standards.',
      'sup_compliance_expertise': 'Compliance and risk control',
      'sup_compliance_whenToUse': 'Compliance assessment, process audit',
      
      // Spatial Computing Department Personnel
      'spatial_xr_name': 'XR Interface Architect',
      'spatial_xr_intro': 'Spatial interaction design, immersive UX',
      'spatial_xr_detail': 'Design understandable interaction systems in AR/VR scenarios.',
      'spatial_xr_expertise': 'XR interaction architecture',
      'spatial_xr_whenToUse': 'XR product design and prototyping',
      
      'spatial_vision_name': 'visionOS Spatial Engineer',
      'spatial_vision_intro': 'Apple Vision Pro native development',
      'spatial_vision_detail': 'Build high-performance spatial applications for visionOS.',
      'spatial_vision_expertise': 'visionOS native development',
      'spatial_vision_whenToUse': 'Vision Pro app building',
      
      'spatial_metal_name': 'macOS Spatial/Metal Engineer',
      'spatial_metal_intro': 'Swift, Metal, high-performance 3D',
      'spatial_metal_detail': 'Build high-frame-rate, low-latency spatial rendering systems.',
      'spatial_metal_expertise': 'Swift + Metal 3D systems',
      'spatial_metal_whenToUse': 'Performance-sensitive spatial computing projects',
      
      // Specialized Department Personnel
      'sp_orchestrator_name': 'Special Agent Orchestrator',
      'sp_orchestrator_intro': 'Multi-agent coordination and workflow management',
      'sp_orchestrator_detail': 'Orchestrate complex tasks and unify multi-role collaboration rhythms.',
      'sp_orchestrator_expertise': 'Multi-agent process orchestration',
      'sp_orchestrator_whenToUse': 'Cross-departmental complex projects',
      
      'sp_mcp_name': 'MCP Builder',
      'sp_mcp_intro': 'MCP server and AI tool extensions',
      'sp_mcp_detail': 'Equip agents with composable, extensible tool capabilities.',
      'sp_mcp_expertise': 'MCP protocol and toolchain',
      'sp_mcp_whenToUse': 'Custom AI capability extensions',
      
      'sp_doc_name': 'Document Generator',
      'sp_doc_intro': 'Automatically generate PDF/PPTX/DOCX/XLSX',
      'sp_doc_detail': 'Quickly produce professional documents from structured content.',
      'sp_doc_expertise': 'Document automation generation',
      'sp_doc_whenToUse': 'Batch reports, solution output',
      
      // Finance Department Personnel
      'fin_bookkeeper_name': 'Bookkeeper & Controller',
      'fin_bookkeeper_intro': 'Monthly closing, reconciliation, GAAP, internal control',
      'fin_bookkeeper_detail': 'Ensure financial records are accurate, auditable, and traceable.',
      'fin_bookkeeper_expertise': 'Financial accounting and internal control',
      'fin_bookkeeper_whenToUse': 'Daily accounting and monthly closing',
      
      'fin_fpa_name': 'FP&A Analyst',
      'fin_fpa_intro': 'Budgeting, rolling forecasts, business analysis',
      'fin_fpa_detail': 'Connect financial and business data to improve decision quality.',
      'fin_fpa_expertise': 'Budgeting and forecasting analysis',
      'fin_fpa_whenToUse': 'Business review, resource allocation',
      
      'fin_tax_name': 'Tax Strategist',
      'fin_tax_intro': 'Tax optimization and cross-regional compliance',
      'fin_tax_detail': 'Optimize tax structure and cash flow under compliance premises.',
      'fin_tax_expertise': 'Tax planning and risk control',
      'fin_tax_whenToUse': 'Tax planning, structure adjustment',
      
      // Academic Department Personnel
      'ac_anthro_name': 'Anthropologist',
      'ac_anthro_intro': 'Cultural systems, kinship, rituals and beliefs',
      'ac_anthro_detail': 'Build culturally and socially systems with internal logic.',
      'ac_anthro_expertise': 'Cultural system modeling',
      'ac_anthro_whenToUse': 'Worldview and social setting',
      
      'ac_history_name': 'Historian',
      'ac_history_intro': 'Historical analysis, periodization, material culture',
      'ac_history_detail': 'Verify historical continuity and period details of settings.',
      'ac_history_expertise': 'Historical coherence verification',
      'ac_history_whenToUse': 'Background setting deepening',
      
      'ac_psych_name': 'Psychologist',
      'ac_psych_intro': 'Personality theory, motivation, cognitive patterns',
      'ac_psych_detail': 'Make character motivations and behaviors more credible and consistent.',
      'ac_psych_expertise': 'Character psychological modeling',
      'ac_psych_whenToUse': 'Character shaping, plot enhancement',
      
      // Game Development Department Personnel
      'game_gameplay_name': 'Gameplay Scripter',
      'game_gameplay_intro': 'Level logic, interaction and numerical rhythm',
      'game_gameplay_detail': 'Build iterable core gameplay loops.',
      'game_gameplay_expertise': 'Gameplay prototyping and scripting',
      'game_gameplay_whenToUse': 'Gameplay verification and level iteration',
      
      'game_tech_name': 'Client Engineer',
      'game_tech_intro': 'Engine integration, performance and multi-platform publishing',
      'game_tech_detail': 'Ensure stable frame rates, resources, and build pipelines.',
      'game_tech_expertise': 'Engine and performance optimization',
      'game_tech_whenToUse': 'Performance bottlenecks and publishing pipelines',
      
      'game_content_name': 'Content Pipeline',
      'game_content_intro': 'Art standards, assets and version coordination',
      'game_content_detail': 'Connect art output with runtime resources.',
      'game_content_expertise': 'Asset and version management',
      'game_content_whenToUse': 'Art integration and resource governance'
    }
  };
  
  const resolved = lang === 'en' ? 'en' : 'zh';
  const pack = translations[resolved] || translations.zh;
  let result = (pack && pack[key]) || translations.zh[key] || key;
  
  // 处理参数替换
  for (const [key, value] of Object.entries(params)) {
    result = result.replace(new RegExp(`\\{\\{\s*${key}\s*\\}\\}`), value);
  }
  
  return result;
}

/**
 * 翻译部门服务（人员）信息
 * @param {Object} service - 部门服务对象
 * @param {string} lang - 语言代码
 * @returns {Object} 翻译后的服务对象
 */
export function translateService(service, lang = getLanguage()) {
  if (!service) return service;
  
  const id = service.id;
  const keyPrefix = id.replace(/-/g, '_');
  
  return {
    ...service,
    name: t(`${keyPrefix}_name`, lang, {}) || service.name,
    intro: t(`${keyPrefix}_intro`, lang, {}) || service.intro,
    detail: t(`${keyPrefix}_detail`, lang, {}) || service.detail,
    expertise: t(`${keyPrefix}_expertise`, lang, {}) || service.expertise,
    whenToUse: t(`${keyPrefix}_whenToUse`, lang, {}) || service.whenToUse
  };
}

/** `data/agentDepartments.js` 的部门 id → `msg_dept_*` 使用的 slug（与 messageDepartmentConfig 一致） */
const AGENT_DEPT_ID_TO_MSG_SLUG = {
  engineering: "engineering",
  design: "design",
  paid: "paid-media",
  sales: "sales",
  marketing: "marketing",
  product: "product",
  pm: "project-management",
  qa: "testing",
  support: "support",
  spatial: "spatial-computing",
  special: "specialized",
  finance: "finance",
  academic: "academic",
  "game-development": "game-development",
};

function msgDeptTitleKeyFromAgentId(agentDeptId) {
  const slug = AGENT_DEPT_ID_TO_MSG_SLUG[agentDeptId];
  if (!slug) return "";
  return `msg_dept_${String(slug).replace(/-/g, "_")}_title`;
}

function msgDeptDescKeyFromAgentId(agentDeptId) {
  const slug = AGENT_DEPT_ID_TO_MSG_SLUG[agentDeptId];
  if (!slug) return "";
  return `msg_dept_${String(slug).replace(/-/g, "_")}_desc`;
}

/**
 * 翻译整个部门信息（包括服务）
 * @param {Object} department - 部门对象
 * @param {string} lang - 语言代码
 * @returns {Object} 翻译后的部门对象
 */
export function translateDepartment(department, lang = getLanguage()) {
  if (!department) return department;

  const titleKey = msgDeptTitleKeyFromAgentId(department.id);
  const descKey = msgDeptDescKeyFromAgentId(department.id);
  let name = department.name;
  let desc = department.desc;
  if (titleKey) {
    const tn = t(titleKey, lang, {});
    if (tn !== titleKey) name = tn;
  }
  if (descKey) {
    const td = t(descKey, lang, {});
    if (td !== descKey) desc = td;
  }

  return {
    ...department,
    name,
    desc,
    services: department.services ? department.services.map((service) => translateService(service, lang)) : [],
  };
}